### ISSUE TITLE
rucksack ppa is missing Xenial (Ubuntu 16.04) packages

### ISSUE THREAD

**Issue by xseignard** [paperManu/splash#14]
Hello,

Correct me if I'm wrong, but the ppa is missing Xenial packages.

Any idea how to  properly install them?

Regards

**Comment by xseignard** [comment]
Could you please update installations instructions? It seems outdated, or at least don't work at all on Ubuntu 16.04.1

Regards

**Comment by paperManu** [comment]
Hello xseignard,

Indeed, I had only updated a part of the README.md after upgrading to Ubuntu 16.04. The documentation has been corrected. Just grab the latest commit in the develop branch, and tell me if this works for you.

Tell me if you encounter any other issue.

**Comment by xseignard** [comment]
Hello,

Thanks for your answer, but there's a bunch of missing dependencies. And no info on where to find them.

So I cannot install splash.

Regards

**Comment by paperManu** [comment]
Well, if you have installed the Debian package, you can just install the runtimes libraries listed for compilation and it should work (your version may vary, but on 16.04 they should be the following):

sudo apt-get install libxrandr2 libxi6 libgsl2 libatlas3-base libzmq5 libsnappy1v5 libgphoto2-6 libglfw3 libxinerama1 libxcursor1 python3-dev libavformat-ffmpeg56 libavcodec-ffmpeg56 libavutil-ffmpeg54 libswscale-ffmpeg3 libportaudio2

 I'll update the README.md to add the dependencies needed when installing this package in the next release.

**Comment by xseignard** [comment]
I tried, but I give up, so much unresolved deps, name conflict with another package and so on.

**Comment by paperManu** [comment]
I did not see such issues when installing it on Ubuntu 16.04. Could you please copy your errors so that I can check what is happening?

**Comment by xseignard** [comment]
So first of all, here is the conflicting package: https://launchpad.net/ubuntu/+source/splash

Then here is the problem I face:
```
Sélection du paquet splash précédemment désélectionné.
(Lecture de la base de données... 274773 fichiers et répertoires déjà installés.
)
Préparation du dépaquetage de splash-0.4.6-Linux.deb ...
Dépaquetage de splash (0.4.6) ...
dpkg: des problèmes de dépendances empêchent la configuration de splash :
 splash dépend de libavformat-dev ; cependant :
  Le paquet libavformat-dev n'est pas installé.
 splash dépend de libavcodec-dev ; cependant :
  Le paquet libavcodec-dev n'est pas installé.
 splash dépend de libboost-system-dev ; cependant :
  Le paquet libboost-system-dev n'est pas installé.
 splash dépend de libglfw3-dev ; cependant :
  Le paquet libglfw3-dev n'est pas installé.
 splash dépend de libgphoto2-dev ; cependant :
  Le paquet libgphoto2-dev n'est pas installé.
 splash dépend de libgsl0-dev ; cependant :
  Le paquet libgsl0-dev n'est pas installé.
 splash dépend de libsnappy-dev ; cependant :
  Le paquet libsnappy-dev n'est pas installé.
 splash dépend de libtool ; cependant :
  Le paquet libtool n'est pas installé.
 splash dépend de libxrandr-dev ; cependant :
  Le paquet libxrandr-dev n'est pas installé.
 splash dépend de libxi-dev ; cependant :
  Le paquet libxi-dev n'est pas installé
dpkg: erreur de traitement du paquet splash (--install) :
 problèmes de dépendances - laissé non configuré
Des erreurs ont été rencontrées pendant l'exécution :
 splash
```

Any idea?

**Comment by paperManu** [comment]
Yes I think I know what is happening. dpkg does not know how to install automatically dependencies, and on top of that another package named splash appeared in Ubuntu 16.04.

I had planned to make another release today, so I'll do it and correct the package name, dependencies and installation instructions in the same run. I'll tell you when it is done.

**Comment by xseignard** [comment]
OK, great! Thanks for your support, and sorry for my grumpy behavior.

Regards

**Comment by paperManu** [comment]
I made the update, and tried it in a vanilla virtual machine. Everything seem to work fine.
You should first clean up any previous installation of Splash:
```
sudo apt remove --purge splash
```

**Comment by xseignard** [comment]
Hello,
So I checked and everything is working OK now! But I still face an issue, I don't have a "Scene" node in the blender addon?

Any idea?

Regards

**Comment by paperManu** [comment]
Indeed, I renamed it to "Graphic card" in the Blender addon and it was not reflected in the wiki. I'll update it as soon as I can. Until then, just use a "Graphic card" node whenever a "Scene" is mentioned :)

**Comment by xseignard** [comment]
Ok! Thanks!

**Comment by xseignard** [comment]
So I tried, and I don't get it, it doesn't export any OBJ and it seems I don't have any camera specs in the json file.
See:
```
// Splash configuration file
// Exported with Blender Splash add-on
{
    "encoding" : "UTF-8",

    "world" : {
        "framerate" : 60
    },
    "scenes" : [
        {
            "name" : "GPU",
            "swapInterval" : 1,
            "display" : 0
        }
    ],
    "GPU" : {
        "Image" : {
            "file" : "",
            "srgb" : 1,
            "flip" : 0,
            "type" : "image",
            "flop" : 0
        },
        "Window" : {
            "srgb" : 1,
            "fullscreen" : -1,
            "type" : "window",
            "decorated" : 0,
            "layout" : [0],
            "position" : [0, 0],
            "size" : [1920, 1080]
        },
        "Object" : {
            "sideness" : 0,
            "type" : "object",
            "color" : [1.0, 1.0, 1.0, 1.0]
        },
        "Camera" : {
            "size" : [1921, 1080],
            "type" : "camera"
        },
        "Mesh" : {
            "file" : "",
            "type" : "mesh"
        },
        "links" : [
            ["Window", "GPU"],
            ["Camera", "Window"],
            ["Object", "Camera"],
            ["Image", "Object"],
            ["Mesh", "Object"]
        ]
    }
}
```

Any idea of what I'm doing wrong?

Regards

**Comment by paperManu** [comment]
I think you did not select a Blender camera in the Splash Camera node. You can do it by selecting a camera in the 3D viewport or in the outliner, and then click on "Select the active camera" on the Splash Camera node.

**Comment by xseignard** [comment]
I actually did it, just tried again, with same results

**Comment by xseignard** [comment]
![stuff](https://cloud.githubusercontent.com/assets/515603/19156472/46dd7b28-8be2-11e6-99c8-f359f390777f.png)

**Comment by paperManu** [comment]
From what I see in your screenshot, you did not click on "Select active camera" : the camera name should be displayed in the "Source" attribute of the Camera node.

Same thing for the Mesh, its name should be displayed in the "Object" attribute.

**Comment by xseignard** [comment]
Well, as I said, I clicked on it. But nothing appears on source?

**Comment by xseignard** [comment]
Ok, if I type the name of the camera and the name of the mesh, my export seem to be ok
```
// Splash configuration file
// Exported with Blender Splash add-on
{
    "encoding" : "UTF-8",

    "world" : {
        "framerate" : 60
    },
    "scenes" : [
        {
            "display" : 0,
            "name" : "GPU",
            "swapInterval" : 1
        }
    ],
    "GPU" : {
        "Window" : {
            "type" : "window",
            "size" : [1920, 1080],
            "srgb" : 1,
            "position" : [0, 0],
            "layout" : [0],
            "decorated" : 0,
            "fullscreen" : -1
        },
        "Sphere" : {
            "type" : "mesh",
            "file" : "splash_Sphere.obj"
        },
        "Object" : {
            "sideness" : 0,
            "type" : "object",
            "color" : [1.0, 1.0, 1.0, 1.0]
        },
        "Camera" : {
            "fov" : 28.841546110078532,
            "type" : "camera",
            "size" : [1921, 1080],
            "eye" : [7.481131553649902, -6.5076398849487305, 5.34366512298584],
            "principalPoint" : [0.5, 0.5],
            "target" : [6.826269626617432, -5.896974086761475, 4.8984198570251465],
            "up" : [-0.31737011671066284, 0.31246861815452576, 0.8953432440757751]
        },
        "Image" : {
            "type" : "image",
            "flop" : 0,
            "flip" : 0,
            "srgb" : 1,
            "file" : ""
        },
        "links" : [
            ["Window", "GPU"],
            ["Camera", "Window"],
            ["Object", "Camera"],
            ["Image", "Object"],
            ["Sphere", "Object"]
        ]
    }
}
```

But if I try to pass it as an arg to splash (e.g. `splash -o myConf.json`), here is the following outpout in the console (and no splash gui appears)
```
	             - Splash -
	- Modular multi-output video mapper -
	          - Version 0.4.8 -

17:35:45 / [WARNING] / World::applyConfig - Non-local scenes are not implemented yet
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
17:35:45 / [MESSAGE] / Listener::initResources - Connected to device: default
17:35:45 / [MESSAGE] / Listener::initResources - Successfully opened PortAudio stream
17:35:45 / [MESSAGE] / LtcClock::LtcClock - Input clock enabled
```

Any idea?

**Comment by paperManu** [comment]
Well, this is why this software needs more users, I can't test everything by myself ;)
Anyway, I just corrected this issue in the develop branch. Just do the following in the splash sources:
```
git checkout develop
git pull origin develop
cd build
make && sudo make install
```

And you should be good to go!

**Comment by xseignard** [comment]
Thanks for your help, I appreciate it!
Now I have the following error:
```
18:38:04 /  [ERROR]  / World::applyConfig - Timeout when trying to connect to scene "GPU". Exiting.
```
Any idea?

**Comment by paperManu** [comment]
I really should have been more careful when cleaning up the Blender addon. Thanks for your patience, I hope the reward will be up to your expectations ;)

I corrected it, do the following inside the Splash directory (yes, I did a force push, the fix was to small for it to have its own commit):
```
git reset --hard HEAD~1
git pull origin develop
make && sudo make install
```

**Comment by xseignard** [comment]
yes! It's working! Thanks!
