### ISSUE TITLE
Mac OS Binary Crashes

### ISSUE THREAD

**Issue by tomh05** [paperManu/splash#15]
I'm on Mac OS 10.11.06 and downloaded the Splash 0.4.10 binary from the releases page.
When I launch splash, it closes as soon as the icon appears in dock, and I see this in console:

06/11/2016 18:12:40.863 com.apple.xpc.launchd[1]: (com.emmanueldurand.splash.408992[34745]) Service exited with abnormal code: 127

Running it from command line I get this:
./run-splash.sh: line 3: cd: /Applications/splash: No such file or directory
dyld: Library not loaded: @rpath/libshmdata-1.3.1.dylib
  Referenced from: /Applications/splash 2.app/Contents/MacOS/./splash
  Reason: image not found
./run-splash.sh: line 4: 35043 Trace/BPT trap: 5       ./splash -o ../Resources/default.json

I'm going to try to install this libary, but in the meantime, shouldn't the release website say this is a dependancy, or give a more helpful error message? (I'd assumed it was optional because docs say" If you want to read video files or feed Splash through Syphon, you can skip this step.")

**Comment by paperManu** [comment]
Hi tomh05,

Yes it is optional, it seems that I built it with this dependency although I should not have. I'll update the package and tell you when it's done.

**Comment by paperManu** [comment]
I updated the archive, this should work better.

**Comment by tomh05** [comment]
Thanks! Works a treat
