### ISSUE TITLE
error with libshmdata

### ISSUE THREAD

**Issue by mvbs23** [paperManu/splash#16]
Hi, everybody.

I installed the repository deb (https://github.com/paperManu/splash/releases/download/0.4.12/splash-0.4.12-Linux.deb) on Ubuntu Mate 16.04. When I try to run it from terminal, it gives me this:

splash: error while loading shared libraries: libshmdata-1.3.so.6: cannot open shared object file: No such file or directory

I tried installing the most recent version of libshmdata, but still the same message appears.

**Comment by paperManu** [comment]
Sorry, this should be fixed now.
