### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by nuclearsugar** [paperManu/splash#17]
There is a broken link in [README.md](https://github.com/paperManu/splash/blob/master/README.md), as seen in the sentence below.
_"And that's it, you can move on the the [Walkthrough](https://github.com/paperManu/splash/blob/master/Walkthrough) page."_

Exiting to see how much you've developed Splash. Really amazing work. Cheers!

**Comment by paperManu** [comment]
Fixed! Thanks for the tip ;)
It will be visible the next time the develop branch is merged in master.

And thanks for the support. Do not hesitate to give me feedback if you use Splash!
