### ISSUE TITLE
Error aftrer crash 0.5.0 on ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by MrWu-at-msv** [paperManu/splash#18]
under ubuntu 16.04 LTS with splash 0.5.0
after crashing (trying moving cursor in camera tab) if i re run splash i get black screen on texture or wire-frame.
log on console:
	             - Splash -
	- Modular multi-output video mapper -
	          - Version 0.5.0 -

16:24:11 / [MESSAGE] / World::applyConfig - Starting an inner Scene
16:24:11 / [MESSAGE] / Scene::init - GL version: 4.3
16:24:11 / [MESSAGE] / Gui::Gui - Framebuffer object successfully initialized
16:24:11 / [MESSAGE] / Camera::init - Framebuffer object successfully initialized
16:24:11 / [MESSAGE] / Camera::init - Camera correctly initialized
16:24:11 / [WARNING] / Camera::loadDefaultModels - File 2d_marker.obj does not seem to be readable.
16:24:11 / [WARNING] / Camera::loadDefaultModels - File 3d_marker.obj does not seem to be readable.
16:24:11 / [WARNING] / Camera::loadDefaultModels - File camera.obj does not seem to be readable.
ALSA lib pcm_dsnoop.c:606:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
16:24:11 / [MESSAGE] / Listener::initResources - Connected to device: default
16:24:11 / [MESSAGE] / Listener::initResources - Successfully opened PortAudio stream
16:24:11 / [MESSAGE] / LtcClock::LtcClock - Input clock enabled
16:24:11 / [MESSAGE] / Camera::init - Framebuffer object successfully initialized
16:24:11 / [MESSAGE] / Camera::init - Camera correctly initialized
16:24:11 / [WARNING] / Camera::loadDefaultModels - File 2d_marker.obj does not seem to be readable.
16:24:11 / [WARNING] / Camera::loadDefaultModels - File 3d_marker.obj does not seem to be readable.
16:24:11 / [WARNING] / Camera::loadDefaultModels - File camera.obj does not seem to be readable.
16:24:11 / [MESSAGE] / Window::Window - Window created successfully
16:24:11 / [MESSAGE] / Window::Window - Render framebuffer object successfully initialized
16:24:11 / [MESSAGE] / Window::setupReadFBO - Read framebuffer object successfully initialized
16:24:12 / [MESSAGE] / Window::Window - Window created successfully
16:24:12 / [MESSAGE] / Window::Window - Render framebuffer object successfully initialized
16:24:12 / [MESSAGE] / Window::setupReadFBO - Read framebuffer object successfully initialized
16:24:12 / [MESSAGE] / Warp::init - Framebuffer object successfully initialized
16:24:12 / [MESSAGE] / Warp::init - Warp correctly initialized
16:24:12 / [WARNING] / Warp::loadDefaultModels - File 3d_marker.obj does not seem to be readable.
16:24:12 / [MESSAGE] / Filter::init - Framebuffer object successfully initialized
16:24:12 / [MESSAGE] / Filter::init - Filter correctly initialized
16:24:12 / [MESSAGE] / Window::setupReadFBO - Read framebuffer object successfully initialized
16:24:12 / [MESSAGE] / Window::setupReadFBO - Read framebuffer object successfully initialized
^C16:25:05 / [MESSAGE] / World::leave - Received a SIG event. Quitting.
16:25:06 / [MESSAGE] / LtcClock::~LtcClock - Input clock disabled

regards

**Comment by paperManu** [comment]
Hi MrWu-at-msv,
Can you give me some precision regarding your computer (GPU + driver especially) and the way you installed Splash (from sources or from the package)?

**Comment by MrWu-at-msv** [comment]
Hi,
spalsh was installed on fresh ubuntu 16.04 LTS  using:
`sudo apt install <download path>/splash-0.5.0-Linux.deb`

GPU: 
```sudo lshw -C display
  *-display               
       description: VGA compatible controller
       product: GM204 [GeForce GTX 970]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:34 memory:f6000000-f6ffffff memory:e0000000-efffffff memory:f0000000-f1ffffff ioport:e000(size=128) memory:f7000000-f707ffff
  *-display
       description: Display controller
       product: Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 06
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm bus_master cap_list
       configuration: driver=i915 latency=0
       resources: irq:30 memory:f7400000-f77fffff memory:d0000000-dfffffff ioport:f000(size=64)
```
Driver proprietary NVIDIA (Xorg.0.log):

```
[    20.152] (II) Module vesa: vendor="X.Org Foundation"
[    20.152] 	compiled for 1.18.1, module version = 2.3.4
[    20.152] 	Module class: X.Org Video Driver
[    20.152] 	ABI class: X.Org Video Driver, version 20.0
[    20.152] (II) NVIDIA dlloader X Driver  367.57  Mon Oct  3 20:03:48 PDT 2016
[    20.152] (II) NVIDIA Unified Driver for all Supported NVIDIA GPUs
[    20.152] (II) NOUVEAU driver Date:   Tue Dec 8 15:52:25 2015 +1000
```

the 2 screen i use for testing hare both on NVIDIA card; i915 is BIOS enabled but not used ATM on this UBUBTU install. Any way i test also with i915 disabled and i had same issue.
i try to run splash with -l option but i don't get any log.

i will try to run with Nvidia Xorg driver and see if something change.

**Comment by paperManu** [comment]
I just noticed some weird thing in your first post, I think the deb package has some issues (some missing 3D models).
You can try installing it from source, I'll fix this later.

**Comment by MrWu-at-msv** [comment]
No the file aren't missing from deb package, on first launch everything work normal but after a crash( or some time even after quiting splash) if i relaunch splash i get the warning of missing .obj you see in first post.
Sometime log out solve the situation some time i need full reboot.

this is the log of first time running splash log
```

	             - Splash -
	- Modular multi-output video mapper -
	          - Version 0.5.0 -

10:33:19 / [MESSAGE] / World::applyConfig - Starting an inner Scene
10:33:20 / [MESSAGE] / Scene::init - GL version: 4.3
10:33:20 / [MESSAGE] / Gui::Gui - Framebuffer object successfully initialized
10:33:20 / [MESSAGE] / Camera::init - Framebuffer object successfully initialized
10:33:20 / [MESSAGE] / Camera::init - Camera correctly initialized
10:33:20 / [WARNING] / Camera::loadDefaultModels - File 2d_marker.obj does not seem to be readable.
10:33:20 / [WARNING] / Camera::loadDefaultModels - File 3d_marker.obj does not seem to be readable.
10:33:20 / [WARNING] / Camera::loadDefaultModels - File camera.obj does not seem to be readable.
10:33:20 / [MESSAGE] / Camera::init - Framebuffer object successfully initialized
10:33:20 / [MESSAGE] / Camera::init - Camera correctly initialized
10:33:20 / [WARNING] / Camera::loadDefaultModels - File 2d_marker.obj does not seem to be readable.
10:33:20 / [WARNING] / Camera::loadDefaultModels - File 3d_marker.obj does not seem to be readable.
10:33:20 / [WARNING] / Camera::loadDefaultModels - File camera.obj does not seem to be readable.
ALSA lib pcm_dsnoop.c:606:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
10:33:20 / [MESSAGE] / Window::Window - Window created successfully
10:33:20 / [MESSAGE] / Window::Window - Render framebuffer object successfully initialized
10:33:20 / [MESSAGE] / Window::setupReadFBO - Read framebuffer object successfully initialized
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
10:33:20 / [MESSAGE] / Listener::initResources - Connected to device: default
10:33:20 / [MESSAGE] / Window::Window - Window created successfully
10:33:20 / [MESSAGE] / Listener::initResources - Successfully opened PortAudio stream
10:33:20 / [MESSAGE] / LtcClock::LtcClock - Input clock enabled
10:33:20 / [MESSAGE] / Window::Window - Render framebuffer object successfully initialized
10:33:20 / [MESSAGE] / Window::setupReadFBO - Read framebuffer object successfully initialized
10:33:20 / [MESSAGE] / Warp::init - Framebuffer object successfully initialized
10:33:20 / [MESSAGE] / Warp::init - Warp correctly initialized
10:33:20 / [WARNING] / Warp::loadDefaultModels - File 3d_marker.obj does not seem to be readable.
10:33:20 / [MESSAGE] / Filter::init - Framebuffer object successfully initialized
10:33:20 / [MESSAGE] / Filter::init - Filter correctly initialized
10:33:20 / [MESSAGE] / Window::setupReadFBO - Read framebuffer object successfully initialized
10:33:20 / [MESSAGE] / Window::setupReadFBO - Read framebuffer object successfully initialized
```

**Comment by paperManu** [comment]
Well, from the logs the obj files are not readable, which most certainly means that it can't find them.
Could you try installing Splash from source? It's quite straightforward, and it will give us a good insight regarding what is happening.

**Comment by paperManu** [comment]
Hi MrWu-at-msv, did you have any chance to test Splash further?

**Comment by paperManu** [comment]
I'll close this since it has been more than a month, but I'll add a ticket to remind me to test the debian package.

**Comment by ekov** [comment]
Hi, i have the same problem, installing Splash from source did not help.

`	             - Splash -
	- Modular multi-output video mapper -
	          - Version 0.5.8 -

2017-03-07T16:54:48 / [MESSAGE] / World::applyConfig - Starting an inner Scene
2017-03-07T16:54:48 / [WARNING] / Scene::glfwErrorCallback - GLX: Failed to create context: GLXBadFBConfig
2017-03-07T16:54:48 / [WARNING] / Scene::glfwErrorCallback - GLX: Failed to create context: GLXBadFBConfig
2017-03-07T16:54:48 /  [ERROR]  / Scene::init - Unable to find a suitable GL version (higher than 4.3)
2017-03-07T16:54:53 /  [ERROR]  / World::applyConfig - Timeout when trying to connect to newly spawned scene "GPU". Exiting.

`

**Comment by ekov** [comment]
`00:01.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Wrestler [Radeon HD 6320] (prog-if 00 [VGA controller])
	Subsystem: Lenovo Wrestler [Radeon HD 6320]
	Flags: bus master, fast devsel, latency 0, IRQ 27
	Memory at e0000000 (32-bit, prefetchable) [size=256M]
	I/O ports at 2000 [size=256]
	Memory at f0200000 (32-bit, non-prefetchable) [size=256K]
	Expansion ROM at <unassigned> [disabled]
	Capabilities: [50] Power Management version 3
	Capabilities: [58] Express Root Complex Integrated Endpoint, MSI 00
	Capabilities: [a0] MSI: Enable+ Count=1/1 Maskable- 64bit+
	Capabilities: [100] Vendor Specific Information: ID=0001 Rev=1 Len=010 <?>
	Kernel driver in use: radeon
	Kernel modules: radeon
`

**Comment by paperManu** [comment]
Hi Ekov,
Please, start a new thread instead of answering to a closed one.
Anyway, you have a AMD card, I strongly suggest you to install the Mesa opensource drivers, and remove the legacy proprietary drivers which are totally outdated. You can get these from here:
https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers
