### ISSUE TITLE
Building splash with homebrew

### ISSUE THREAD

**Issue by eighteight** [paperManu/splash#2]
homebrew is preferred way to install on mac (rather than ports).

please add instructions on how to use homebrew for spash installation

**Comment by paperManu** [comment]
Hi eighteight,

I don't have an OSX computer with Homebrew installed so I can't test it, but after a quick check all the librairies needed by Splash seem to be packaged for Homebrew except OpenImageIO. So the situation is similar to MacPorts.

I did a very small update to the documentation (in the Wiki or the develop branch)  to reflect this, but if you could test it on your side it would be greatly appreciated. The package names are not exactly identical I think but once again I can't test it.

**Comment by eighteight** [comment]
Hi Emmanuel, 

I was able to use homebrew to install the packages you are describing vis-a-vis macports. I then hit the problem making shmdata:

'''eightlocal:shmdata eight$ make && sudo make install
/Applications/XCode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in shmdata
make[2]: Nothing to be done for `all'.
Making all in utils
make[2]: Nothing to be done for `all'.
Making all in tests
make[2]: Nothing to be done for `all'.
Making all in wrappers
Making all in python
glibtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../..     `python3.4-config --cflags` -I../.. -g -O2 -std=c++11 -D__Darwin -g3 -ggdb -Wall -Wextra -Wfatal-errors -Wno-unused-parameter -MT pyshmdata_la-pyshmdata.lo -MD -MP -MF .deps/pyshmdata_la-pyshmdata.Tpo -c -o pyshmdata_la-pyshmdata.lo `test -f 'pyshmdata.cpp' || echo './'`pyshmdata.cpp
/bin/sh: python3.4-config: command not found
glibtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../.. -I../.. -g -O2 -std=c++11 -D__Darwin -g3 -ggdb -Wall -Wextra -Wfatal-errors -Wno-unused-parameter -MT pyshmdata_la-pyshmdata.lo -MD -MP -MF .deps/pyshmdata_la-pyshmdata.Tpo -c pyshmdata.cpp  -fno-common -DPIC -o .libs/pyshmdata_la-pyshmdata.o
In file included from pyshmdata.cpp:15:
./pyshmdata.h:20:10: fatal error: 'Python.h' file not found
#include <Python.h>
         ^
1 error generated.
make[3]: *** [pyshmdata_la-pyshmdata.lo] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
eightlocal:shmdata eight$ 
'''

I have installed python3 using homebrew, but it still can't find the header.

**Comment by paperManu** [comment]
I'll keep this in mind and check what's wrong with shmdata with its main developer.

In the meantime, you should know that shmdata is not mandatory. It is used to communate with some of our other softwares and if you plan to read videos or feed Splash through Syphon, you won't need it.

So you can go ahead with compiling Splash without it. I'll update the documentation to make this clearer.

**Comment by eighteight** [comment]
I went ahead, and I think was able to install all dependencies (with a caveat 
```
$ brew tap homebrew/versions
$ brew install --build-bottle --static glfw3
```

Then splash build fails with 

```
checking for snappy-c.h... yes
checking json/reader.h usability... no
checking json/reader.h presence... no
checking for json/reader.h... no
configure: error: Missing JsonCPP
```

However, brew believes jsoncpp is installed:

```
eightlocal:splash eight$ brew install jsoncpp
Warning: jsoncpp-0.10.5 already installed
eightlocal:splash eight$ 

```

**Comment by paperManu** [comment]
Hum OK, it looks like Homebrew places jsoncpp in a weird place (compared to Linux and MacPorts). I expect it to be in /usr/local/json, not /usr/local/jsoncpp/json.

I added a workaround for this (in the develop branch), could you please test it?

**Comment by eighteight** [comment]
That step is now OK. The next one is broken due to zmq dependency:

Making all in src
/Applications/XCode.app/Contents/Developer/usr/bin/make  all-am
glibtool --tag=CXX  --tag=CXX   --mode=compile clang++ -DHAVE_CONFIG_H -I. -I../include  -funroll-loops -ftree-vectorize -I../include -I../external/imgui -I../external/hap/source -I../external/piccante/include -DGLM_FORCE_RADIANS -DDATADIR=\"/usr/local/share/splash/\" -DSPLASHPREFIX=\"/usr/local\" -I../external/glad/compatibility/include  -I../external/syphon/build/Release/Syphon.framework/Headers/Syphon.h -I/usr/local/include -I/usr/local/include/jsoncpp -I../external/bandit/bandit  -I/usr/local/Cellar/glfw3/3.1.1/include    -I/usr/local/Cellar/gsl/1.16/include   -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx  -I/usr/local/Cellar/zeromq/4.1.3/include     -I/usr/local/Cellar/opencv/2.4.12/include/opencv -I/usr/local/Cellar/opencv/2.4.12/include     -F../external/syphon/build/Release -framework Syphon -g -O2 -std=c++11 -D__Darwin -I/usr/local/include -I/usr/local/include/jsoncpp -MT libsplash_0.3_la-camera.lo -MD -MP -MF .deps/libsplash_0.3_la-camera.Tpo -c -o libsplash_0.3_la-camera.lo `test -f 'camera.cpp' || echo './'`camera.cpp
glibtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I../include -funroll-loops -ftree-vectorize -I../include -I../external/imgui -I../external/hap/source -I../external/piccante/include -DGLM_FORCE_RADIANS -DDATADIR=\"/usr/local/share/splash/\" -DSPLASHPREFIX=\"/usr/local\" -I../external/glad/compatibility/include -I../external/syphon/build/Release/Syphon.framework/Headers/Syphon.h -I/usr/local/include -I/usr/local/include/jsoncpp -I../external/bandit/bandit -I/usr/local/Cellar/glfw3/3.1.1/include -I/usr/local/Cellar/gsl/1.16/include -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -I/usr/local/Cellar/zeromq/4.1.3/include -I/usr/local/Cellar/opencv/2.4.12/include/opencv -I/usr/local/Cellar/opencv/2.4.12/include -F../external/syphon/build/Release -framework Syphon -g -O2 -std=c++11 -D__Darwin -I/usr/local/include -I/usr/local/include/jsoncpp -MT libsplash_0.3_la-camera.lo -MD -MP -MF .deps/libsplash_0.3_la-camera.Tpo -c camera.cpp  -fno-common -DPIC -o .libs/libsplash_0.3_la-camera.o
clang: warning: -framework Syphon: 'linker' input unused
In file included from camera.cpp:1:
In file included from ../include/camera.h:42:
In file included from ../include/basetypes.h:34:
../include/link.h:35:10: fatal error: 'zmq.hpp' file not found
#include <zmq.hpp>
         ^
1 error generated.
make[2]: *** [libsplash_0.3_la-camera.lo] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
eightlocal:splash eight$ brew install zmq
Warning: zeromq-4.1.3 already installed
eightlocal:splash eight$ locate zmq.hpp
/Applications/Vuo Editor.app/Contents/Frameworks/Vuo.framework/Versions/1.1.0/Headers/zmq/zmq.hpp
eightlocal:splash eight$ locate zmq.h
/Applications/Vuo Editor.app/Contents/Frameworks/Vuo.framework/Versions/1.1.0/Headers/zmq/zmq.h
/Applications/Vuo Editor.app/Contents/Frameworks/Vuo.framework/Versions/1.1.0/Headers/zmq/zmq.hpp
/usr/local/Cellar/zeromq/4.1.3/include/zmq.h
/usr/local/include/zmq.h
eightlocal:splash eight$

**Comment by paperManu** [comment]
It looks like you do have ZMQ, but not the c++ bindings. It looks like there is a package named zmqpp, and also one named cppzmq. One of those may do the trick.

**Comment by eighteight** [comment]
Both zmq and zmqpp are installed, while brew does not have formula for cppzmq:

```
eightlocal:splash eight$ brew search cppzmq
No formula found for "cppzmq".
==> Searching pull requests...
eightlocal:splash eight$ 
```

And then, there is this: https://github.com/zeromq/cppzmq –– is it the one?

**Comment by paperManu** [comment]
Yes that's it. It looks like zmqpp is another c++ binding, although not the one packaged in Ubuntu or MacPorts.

I think you can place zmq.hpp in /usr/local/include. I should add it as a submodule to ease the process though.

**Comment by eighteight** [comment]
At the end of sudo make install I get :

cp -r ../external/syphon/build/Release/Syphon.framework ./splash.app/Contents/Frameworks/Syphon.framework
DYLD_LIBRARY_PATH=/usr/local/lib:/opt/local/lib:/usr/local/lib:YLD_LIBRARY_PATH dylibbundler -cd -od -b \
		-x ./splash.app/Contents/MacOS/splash \
		-x ./splash.app/Contents/MacOS/splash-scene \
		-d ./splash.app/Contents/libs/
* Collecting dependenciessh: line 1: 32473 Trace/BPT trap: 5       /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk / -find otool 2> /dev/null
otool: error: unable to find utility "otool", not a developer tool or in PATH
Cannot find file ./splash.app/Contents/MacOS/splash to read its dependencies
make[1]: *** [install] Error 1
make: *** [install-recursive] Error 1



eightlocal:splash eight$ which otool
/usr/bin/otool
eightlocal:splash eight$ otool
Usage: /Applications/XCode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool [-arch arch_type] [-fahlLDtdorSTMRIHGvVcXmqQjCP] [-mcpu=arg] [--version] <object file> ...
	-f print the fat headers
	-a print the archive header
	-h print the mach header
	-l print the load commands
	-L print shared libraries used
	-D print shared library id name
	-t print the text section (disassemble with -v)
	-p <routine name>  start dissassemble from routine name
	-s <segname> <sectname> print contents of section
	-d print the data section
	-o print the Objective-C segment
	-r print the relocation entries
	-S print the table of contents of a library
	-T print the table of contents of a dynamic shared library
	-M print the module table of a dynamic shared library
	-R print the reference table of a dynamic shared library
	-I print the indirect symbol table
	-H print the two-level hints table
	-G print the data in code table
	-v print verbosely (symbolically) when possible
	-V print disassembled operands symbolically
	-c print argument strings of a core file
	-X print no leading addresses or headers
	-m don't use archive(member) syntax
	-B force Thumb disassembly (ARM objects only)
	-q use llvm's disassembler (the default)
	-Q use otool(1)'s disassembler
	-mcpu=arg use `arg' as the cpu for disassembly
	-j print opcode bytes
	-P print the info plist section as strings
	-C print linker optimization hints
	--version print the version of /Applications/XCode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool
eightlocal:splash eight$

**Comment by paperManu** [comment]
This has something to do with dylibbundler, which uses otool to modify the dependencies path in each library and executable files.

You may have to restart your terminal for dylibbundler to run correctly... or restart the whole computer, but that would be a bit extreme.

**Comment by eighteight** [comment]
Restarting did not help. I then followed this advice on switching command tools http://stackoverflow.com/a/30902106/3593407  That moved me further to where it started complaining about not finding bunch of symlinks (although checking them manually did not find anything wrong with them) and it stopped complaining about libhd5.9.dylib. Since I have libh5.10.dylib, I symlinked that. and it seemed to continue, but then it failed. Unfortunately, this is where I have a hard stop.

**Comment by paperManu** [comment]
Can you try compiling everything with the build_osx.sh script?

**Comment by eighteight** [comment]
```
git clone https://github.com/paperManu/splash.git
cd splash/
git checkout develop
git pull
history | grep git
git submodule update --init
./build_osx.sh

```
...
* Checking output directory ./splash.app/Contents/libs/
* Creating output directory ./splash.app/Contents/libs/
    mkdir -p ./splash.app/Contents/libs/
    cp -n /tmp/lib/libsplash-0.3.0.dylib  ./splash.app/Contents/libs/libsplash-0.3.0.dylib 
    chmod +w ./splash.app/Contents/libs/libsplash-0.3.0.dylib 
    install_name_tool -id @executable_path/../libs/libsplash-0.3.0.dylib  ./splash.app/Contents/libs/libsplash-0.3.0.dylib 
sh: line 1: 49181 Trace/BPT trap: 5       /Applications/XCode.app/Contents/Developer/usr/bin/xcodebuild -sdk / -find install_name_tool 2> /dev/null
install_name_tool: error: unable to find utility "install_name_tool", not a developer tool or in PATH


Error : An error occured while trying to change identity of library ./splash.app/Contents/libs/libsplash-0.3.0.dylib 
make[1]: *** [install] Error 1
make: *** [install-recursive] Error 1
eightlocal:splash eight$

**Comment by eighteight** [comment]
i have a few minutes, if you'd like we could get on skype –– it's seems it's pretty close

**Comment by paperManu** [comment]
So it now finds otool, but not install_name_tool?

Indeed it seems to be very close, I don't understand why you have problems with these tools as they are part of the XCode command line tools, not Homebrew.

If you want, you can connect on IRC on Freenode, channel ##splash (note the two #). I'm usually there.

**Comment by paperManu** [comment]
Also,

**Comment by paperManu** [comment]
Also, I didn't mention it earlier, but you can find some pre-built OSX bundles right there:
https://github.com/paperManu/splash/releases

These are not the latest development version, but they work as-is on OSX 10.9 and up.

**Comment by mike-iv** [comment]
Hello! 
Install with macports, at first had problems with syphon. I copied lost files to the correct directory and syphon started to work, but still something wrong. Please help me :)


Check dependencies

** BUILD SUCCEEDED **

/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
make[2]: *** No rule to make target `../external/imgui/imgui.cpp', needed by `libsplash_0.3_la-imgui.lo'.  Stop.
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

**Comment by paperManu** [comment]
I'll close this issue, as I have updated the documentation to correct some errors for the OSX installation. It does not cover the Homebrew specific packages though, as I don't have a computer to find the good ones.
