### ISSUE TITLE
Mesa OpenGL 3.3 version

### ISSUE THREAD

**Issue by skankerror** [paperManu/splash#21]
Hi paperManu, 

I can't get splash running on linux 64 bit. splash 0.5.2 from git.
[ray@manjaro build]$ glxinfo | grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
**OpenGL core profile version string: 3.3 (Core Profile) Mesa 13.0.3
OpenGL core profile shading language version string: 3.30**
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
**OpenGL version string: 3.0 Mesa 13.0.3**
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 13.0.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:

The problem is that my OpenGL version string is 3.0, but my core profile version string is 3.3 which would be enough to run splash ??

I get an error because splash checks version string and close. Would it be possible to check core profile version string and run ?

**Comment by paperManu** [comment]
Splash needs at least OpenGL 4.3. It used to work with less but the current blending algorithm needs compute shader. And as OpenGL 4.3 is now very common (even on integrated GPUs) I didn't see any reason to keep supporting OpenGL 3.3.

Anyway, your Mesa driver is not up to date. Mesa 13.1 supports OpenGL 4.5 with AMD graphic cards, you should update your driver (see the [Mesa matrix](http://mesamatrix.net/)) I already used AMD GPUs with Splash and it works quite well.

**Comment by skankerror** [comment]
I updated to mesa 17.1, with OpenGL 4.5 and tha works ! thanks.
