### ISSUE TITLE
'context not defined' when trying to export configuration from blender

### ISSUE THREAD

**Issue by tari3x** [paperManu/splash#24]
Trying both "Export configuration" and "Export project" in the world node results in
```
Traceback (most recent call last):
  File "/home/avatar/.config/blender/2.76/scripts/addons/splash/operators.py", line 360, in execute
    return self.export(self.export_project)
  File "/home/avatar/.config/blender/2.76/scripts/addons/splash/operators.py", line 426, in export
    args = self.scene_lists[scene][node].exportProperties(self.filepath)
  File "/home/avatar/.config/blender/2.76/scripts/addons/splash/nodes.py", line 330, in exportProperties
    editedObject = context.edit_object.name
NameError: name 'context' is not defined
```
I would upload the blender project, but not sure how to.

**Comment by paperManu** [comment]
Could you send me your blend file so that I can see what is wrong with it?

**Comment by tari3x** [comment]
I don't see a way to upload a file on gihub, and I'm too stupd to find your contact details anywhere.

**Comment by tari3x** [comment]
Try this: http://ge.tt/3vLGkqi2

**Comment by paperManu** [comment]
Thanks. It looks like it fails to export whenever an object is in edit mode. I'll correct that, but until then you can go back to object mode and the export will work.

**Comment by tari3x** [comment]
worked, thanks!
