### ISSUE TITLE
splash spins at 70% CPU when idle

### ISSUE THREAD

**Issue by tari3x** [paperManu/splash#26]
That's pretty much it. 

inputs: http://ge.tt/5xIQrsi2

**Comment by paperManu** [comment]
Well, that's normal: Splash is a realtime rendering software, and as such keeps its framerate to 60fps (or whatever it is set through the swapInterval Scene attribute) even when there is not much which changed.

I may one day change this and detect when nothing has been updated, but the usual case is to play films or realtime captured content, so this is not really a priority.
