### ISSUE TITLE
compiling in ubuntu 15.04

### ISSUE THREAD

**Issue by nanu-c** [paperManu/splash#3]
the
```/bin/bash ../libtool  --tag=CXX   --mode=link clang++  -g -O2 -std=c++11 -I/usr/include/jsoncpp -I/usr/local/include/jsoncpp ../src/libsplash-0.3.la   -o splash-check-calibration splash-check-calibration.o```

is missing a ```-lpthread```

and I don't know how to include it

**Comment by paperManu** [comment]
The tools subdirectory is only useful to me, so I deactivated it.
Just grab the develop branch and recompile everything:
  git checkout develop
  git pull origin develop
  make

**Comment by nanu-c** [comment]
okey i did some research but i end up in errors regarding the ffmpeg/libav problematic.
```
git clone https://github.com/paperManu/splash.git
cd splash
git checkout develop
git pull origin develop
./autogen.sh 
./configure
make
```

```
In file included from camera.cpp:7:
In file included from ../include/scene.h:38:
In file included from ../include/colorcalibrator.h:35:
../include/cgUtils.h:29:10: fatal error: 'hap.h' file not found
#include <hap.h>
         ^
1 error generated.
Makefile:1470: recipe for target 'libsplash_0.3_la-camera.lo' failed
```
The libavcodec-ffmpeg-dev doesn't include the hap.h file, it is also not part of libavcodec-dev from libav. Also libavcodec-ffmpeg-dev breaks my opencv...
The I downloaded the  most recent version of ffmpeg and referenced the headerfiles.
```
./configure CXXFLAGS="-I/home/nanu/Schreibtisch/ffmpeg-2.8/libavcodec"
```
```
In file included from camera.cpp:7:
In file included from ../include/scene.h:38:
In file included from ../include/colorcalibrator.h:35:
In file included from ../include/cgUtils.h:29:
/home/nanu/Schreibtisch/ffmpeg-2.8/libavcodec/hap.h:61:14: error: expected member name or ';' after declaration specifiers
    AVClass *class;
    ~~~~~~~  ^
In file included from camera.cpp:7:
In file included from ../include/scene.h:38:
In file included from ../include/colorcalibrator.h:35:
../include/cgUtils.h:153:24: error: unknown type name 'HapDecodeWorkFunction'
void hapDecodeCallback(HapDecodeWorkFunction func, void* p, unsigned int count, void* info);
                       ^
In file included from camera.cpp:7:
In file included from ../include/scene.h:42:
../include/gui.h:39:10: fatal error: 'imgui.h' file not found
#include <imgui.h>
         ^
3 errors generated.
```

**Comment by paperManu** [comment]
A few of the needed library are included as submodules, this is the case of Hap and ImGui.
You need to do the following to check them out:
```
git submodule update --init
```

**Comment by paperManu** [comment]
Also, do you follow closely the instructions from the installation wiki?

https://github.com/paperManu/splash/wiki/Installation

**Comment by nanu-c** [comment]
I was reading the installation guide, but this try I missed the git submodule update --init
Nevertheless I have some thoughts on the guide
the two mentioned ppa:
```
sudo apt-add-repository ppa:irie/blender
sudo apt-add-repository ppa:sat-metalab/metalab
```
the command `sudo apt-add-repository ` isn't working without further configuration, because the blender repro isn't maintained since 2014 and also the metlab doesn't include explicit releases for vivid. So I changed matlab to devel and the blender to 
```
sudo apt-add-repository  ppa:thomas-schiex/blender
```
and finally I compiled ffmpeg with `./configure --enable-shared` because i got the error
```
/usr/local/lib/libavformat.a(allformats.o): relocation R_X86_64_32 against `ff_a64_muxer' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libavformat.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:1304: recipe for target 'libsplash-0.3.la' failed
```
It finish the compiling process but then I get a `Speicherzugriffsfehler (Speicherabzug geschrieben)
`
With valingrid the backtrace names `libIlmImf-2_2.so.22.0.0` responsible for the break which is part of  OpenEXR and required by libopenimageio-dev. So this is maybe not working with `ppa:thomas-schiex/blender` Tomorrow I try again and report the results later.

**Comment by nanu-c** [comment]
last error from valgrind https://gist.github.com/nanu-c/386c82e675cb24e6a1d2

**Comment by paperManu** [comment]
Hi Nanu-c,

Thanks for pointing this to me, I did not test the compilation for anything beyond Ubuntu 14.04 and was not aware of these issues. I just updated the README.md as well as the Installation wiki so that it should compile on Ubuntu 15.04 as well. I tested it in a virtual machine and it goes smoothly (except for some new warnings which I'll have to take care of).

Let me know how it goes for you.

**Comment by nanu-c** [comment]
Today I tried everything in the installation guide in an new vm from virtualboximages and i got the same error.
`Segmentation fault (core dumped)`
Then I thought try to install it via the metalab repro, but there is another program called splash in the official repros: `http://users.monash.edu.au/~dprice/splash/`
When i disable the official repros then I get the error:
`Depends: libopenimageio1.3 but it is not going to be installed` because this is in the irie and in the new blender repro it is  libopenimageio1.4

**Comment by paperManu** [comment]
Splash does not seem to run in a VM, probably because it can not find a suitable OpenGL driver. I did not do any test to make it run in a VM as it does not make much sense, I only use VirtualBox to test compilation.

Speaking of which, which kind of graphic card do you have, and did you install the graphic driver?

**Comment by nanu-c** [comment]
I am working at the moment on my laptop with a not so fast Intel HD Graphics 4000 which supports OpenGL 4.

**Comment by paperManu** [comment]
I tested it on a Intel HD 5500 and it runs OK, using OpenGL 3.3 on Linux Mint 17.2 (roughly equivalent to Ubuntu 14.04).

**Comment by paperManu** [comment]
I close this issue as compilation should now work, according to my tests.
