### ISSUE TITLE
splash crashes

### ISSUE THREAD

**Issue by mike-iv** [paperManu/splash#34]
Hello! Just installed splash on linux ubuntu.

The problem is...
I'm in camera window(GUI) and when I'm try to choose the vertex in wareframe mode, there is no sphere appear around that point and splash crashes.

**Comment by paperManu** [comment]
Hi mike-iv,
How did you install Splash? With the package?

**Comment by mike-iv** [comment]
Thanks for the fast answer. I've got the deb package from here https://github.com/paperManu/splash/releases and install it without any errors.

**Comment by paperManu** [comment]
There is any issue with the package currently, it lacks some asset files.
Until I correct it, you should try compiling it by yourself, it is more straight-forward than it seems.

**Comment by mike-iv** [comment]
I'm trying to compile. Everything works except the last step

**make && sudo make install**

The process crushes with fatal error: 

**GL/gl.h: No such file or directory**

Here is the full log: 

**/home/andrew/splash/external/glfw/include/GLFW/glfw3.h:171:21: fatal error: GL/gl.h: No such file or directory
compilation terminated.
src/CMakeFiles/splash-0.6.dir/build.make:62: recipe for target 'src/CMakeFiles/splash-0.6.dir/world.cpp.o' failed
make[2]: *** [src/CMakeFiles/splash-0.6.dir/world.cpp.o] Error 1
CMakeFiles/Makefile2:383: recipe for target 'src/CMakeFiles/splash-0.6.dir/all' failed
make[1]: *** [src/CMakeFiles/splash-0.6.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2**

What can you say about this? Why this header file is missing? Thank you for your time.

**Comment by paperManu** [comment]
You seem to be missing the GL header files from your OpenGL driver. You could either install mesa-common-dev or the package related to your driver (like nvidia-xxx-dev, xxx being the driver version)

**Comment by paperManu** [comment]
Hi mike-iv,
Just to let  you know that I fixed the issue with the package, and that it should be in the next release (0.6.4).
