### ISSUE TITLE
Build fails on macOS Sierra

### ISSUE THREAD

**Issue by romanrandom** [paperManu/splash#37]
Hi, your project looks really exciting!
I'd like to try it for a performance but I get these errors when building:

factory.cpp:391:24: error: cannot deduce lambda return type
      from initializer list
                return { nullptr }

factory.cpp:393:24: error: no viable conversion from
      returned value of type 'typename enable_if<!is_array<BaseObject>::value &&
      !is_array<Texture_Syphon>::value, shared_ptr<BaseObject> >::type' (aka
      'std::__1::shared_ptr<Splash::BaseObject>') to function return type 'auto'
  ...dynamic_pointer_cast<BaseObject>(make_shared<Texture_Syphon>(_root));

factory.cpp:388:37: error: no matching constructor for
      initialization of 'Splash::Factory::Page'
    _objectBook["texture_syphon"] = Page(

I know you don't support Mac but maybe it's something I did wrong. Any suggestion please?

**Comment by paperManu** [comment]
Hi romanrandom,
I pushed a (possible) fix in the bug/clang-compilation-error branch.
Could you try it?

**Comment by romanrandom** [comment]
It built! Thank you! But now I have issue https://github.com/paperManu/splash/issues/30

**Comment by paperManu** [comment]
Cool. Yes there is an issue with the bundled libraries, it might not be hard to correct for someone who knows OSX...

**Comment by romanrandom** [comment]
I'll try to find a solution!
