### ISSUE TITLE
Getting video sound working

### ISSUE THREAD

**Issue by Looo911** [paperManu/splash#38]
Hey,

I have a problem getting the sound working. I don`t know what exactly to write into the "audioDeviceOutput"-field. Do you have any tips or a tutorial etc? 

Thanks for your help & your great work.

**Comment by paperManu** [comment]
Hi Looo911,

By default, Splash will output the sound to the default PulseAudio output device. You can check if it's working with a tool like pavucontrol, which lists all the clients connected to Pulse.

The "audioDeviceOutput" field allows for selecting another output device, and is especially dedicated towards sending the audio to a Jack client. If you don't use Jack, you don't have to worry about this.

Also, if you look in the console when loading a video file, it gives a bunch of information about the streams contained in the video. Look for anything related to "Speaker" or "Sound_Engine".

I hope this helps.
Manu

**Comment by Looo911** [comment]
Thanks for your response, got it working now. HDMI was set as default and I used the other programs via JACK, so this was the only one which didn`t. Got my soundcard as default and it seems to work via PulseAudio, but I still don`t know how to get it working via JACK. But that isn`t that important right now.

**Comment by paperManu** [comment]
If you have a jackd server running, it should connect to it automatically. But if you don't set anything as the audioDeviceOutput, it won't ask Jack  to connect it to anything (not even the system outputs). You can do it by hand through qjackctl or using jack_connect.
