### ISSUE TITLE
glm/glm.hpp: present but cannot be compiled

### ISSUE THREAD

**Issue by tedr56** [paperManu/splash#4]
Hi.
I'm trying to build this promising Splash on LinuxMint 17.2, based on Ubuntu 14.04 and I'm getting this error from glm.

https://gist.github.com/tedr56/37634f151ac7b97fdaa8

```
configure: WARNING: glm/glm.hpp: present but cannot be compiled
configure: WARNING: glm/glm.hpp:     check for missing prerequisite headers?
configure: WARNING: glm/glm.hpp: see the Autoconf documentation
configure: WARNING: glm/glm.hpp:     section "Present But Cannot Be Compiled"
configure: WARNING: glm/glm.hpp: proceeding with the compiler's result
configure: WARNING:     ## --------------------------------------- ##
configure: WARNING:     ## Report this to                          ##
configure: WARNING:     ## --------------------------------------- ##
checking for glm/glm.hpp... no
configure: error: Missing glm
```

From [here](http://is.gd/K2ue92), I understand there is missing headers which can be added in configure.ac but my knowledge stops here.

I tried with my apt glm at version 0.9.5.1.
Then with the last [0.9.7](http://glm.g-truc.net/0.9.7/index.html), and I get the same error.

Thanks for any help.

**Comment by paperManu** [comment]
Hi tedr56,

This is strange, I work mainly on Linux Mint 17.2 these days and I have usually no issue compiling Splash (and I don't even talk about merely completing the configure step).

But I'm curious which kind of configuration you have: it seems from the gist that your CPU does not support any variant of SSE or MMX, which is odd to say the least. Could you give me some information about you configuration?

**Comment by paperManu** [comment]
OK, I just did a test in a virtual machine and here is what I found.

I don't use GCC but Clang for compiling Splash (for various reasons). It seems that if you don't have Clang installed, you get the kind of output from configure that we see in your gist. So I think that you did not install Clang on your system.

Did you follow closely the installation steps from the wiki? You can find it here: https://github.com/paperManu/splash/wiki/Installation#linux

Please tell me whether this solves your issue.

**Comment by tedr56** [comment]
Glad you found it.

I do have Clang installed, but not the basic meta-papckage with 3.4 version, but clang-3.6.
I thought it would work. Did on other projects.
I'll give a try to meta.

**Comment by tedr56** [comment]
All good. https://gist.github.com/tedr56/95fb19019d28d9b36f12

So it can't work with clang-3.6, or it get undetected?

**Comment by paperManu** [comment]
I have not made much tests with clang-3.6 on Mint 17.2, my guess is that this package does not create a symlink to /usr/bin/clang. But once again I prefer using what is "standard" on the system, the dependencies are already hard enough to get right.
