### ISSUE TITLE
Can't build on debian buster

### ISSUE THREAD

**Issue by RezaSR** [paperManu/splash#43]
Hello
I get error while building. I am not familiar with cmake and build system, please help me.

OS: Debian GNU/Linux testing (buster)
Kernel: 4.12.0-2-amd64
gcc: 7.2.0

Error:
https://paste.debian.net/988579

**Comment by paperManu** [comment]
Hi RezaSR,
From the error messages, it looks like you did not run the make_deps.sh script at the root of the sources first?

**Comment by RezaSR** [comment]
Hi, thanks for your quick reply.
I executed make_deps.sh before building.

Now I removed package libportaudio2, so "HAVE_PORTAUDIO" was evaluated to 0 and now there is no error. But without portaudio feature, I have no idea what is it about?

Thanks for your help

**Comment by paperManu** [comment]
Without Portaudio, Splash won't be able to play sound, and won't be able to read the LTC clock from any input. So no sync with an external sound source.

You say to remove the package portaudio2, but the right package to install is portaudio19-dev, which is more recent than portaudio2. There is a good chance that this will solve your issue.

Regarding the ```functional``` header, thanks for the tip, I'll add it in my next commit.

**Comment by RezaSR** [comment]
Unfortunately, installing portaudio19-dev didn't help.
Actually the version of installed library libportaudio2 was (19.6.0-1) https://packages.debian.org/buster/libportaudio2

**Comment by paperManu** [comment]
I'll have to check it myself with a Debian installation, it seems that the packages are different and I can't give you a solution right now.

**Comment by RezaSR** [comment]
It was compiled correctly on Debian stable (stretch) with gcc 6.
I'll check it more on Debian testing (buster) and let you know if solved the problem.

Thanks

**Comment by RezaSR** [comment]
I compiled on a new buster installation and it was compiled with no error.
Of course as I mention earlier, the  <functional> must be added.

Thanks

**Comment by paperManu** [comment]
Hi RezaSR,
I had the chance to test Splash on Ubuntu 17.10, and I may have fixed your issue. In 17.10, Wayland is the default display server and with some window managers Xorg is also running. If so, the display server ID may not be :0, which leads to issues with Splash. After updating Splash to the version of the branch bug/ubuntu-17.10, check it with this command:

```
echo ${DISPLAY}
```

If it does not return :0, but for example :1, run Splash with the following command:

```
splash -S 1
```

This should force the display server to the one with ID 1.

**Comment by RezaSR** [comment]
Thanks alot

**Comment by paperManu** [comment]
It has been merged into develop, and should be in the master branch in a couple of weeks!
