### ISSUE TITLE
Passing realtime rendered glsl to splash

### ISSUE THREAD

**Issue by rohtie** [paperManu/splash#44]
Hi!

I am working on a [small desktop program](https://github.com/rohtie/Shikaku) similar to shadertoy for live coding glsl shaders. 
Is there a way to pass my realtime rendered output to splash?

The first thought I had was piping my output to a video file by passing rendered frames to ffmpeg and then opening that file in splash, but I imagine that would be quite a big overhead and not really suitable for realtime visuals.

I really want my program to be able to integrate with splash, do you have any ideas?

Edit: 
Reading a bit more, it seems that splash supports communication through Shmdata, which sounds more reasonable than piping through ffmpeg. 
Can you give a simple example of how to hook a c++ opengl program with splash? Or maybe some pointers in the right direction? As I can't find any documentation on how to use shmdata.

**Comment by paperManu** [comment]
Hi rohtie,
Indeed this seems like the typical use for Shmdata. There an example of such a use (grab frames from OpenGL and send them through Shmdata) inside Splash:

* [Grab GL frame](https://github.com/paperManu/splash/blob/master/src/sink.cpp)
* [Send the frame through shmdata](https://github.com/paperManu/splash/blob/master/src/sink_shmdata.cpp)

I'll assemble an example when I have more time for this.

**Comment by rohtie** [comment]
Thank you!
