### ISSUE TITLE
Missing dependencies for debian

### ISSUE THREAD

**Issue by wargreen** [paperManu/splash#45]
Hello,
A try to install your released .deb show a dependency problem with theses packages :
libboost-system1.58.0 (is it lots of version, 54-63, but not 58)
libopencv-highgui2.4v5 (libopencv-highgui2.4 exist in jessie and sid)
libgsl2 (don't seem build for 386/amd64 anymore)

Thanks for your code !

**Comment by paperManu** [comment]
Hello wargreen,
Some package names are different on Ubuntu and on Debian. I don't know of a work around for this, so you have two options:
- compile Splash from the sources, which is fairly straightforward even on Debian
- install the package you have (libgsl23, and a version of Boost close to the one listed in the dependencies), and install the package with dpkg which as far as I know does not check the dependencies.

Also, I removed the dependency to OpenCV as the package is not compiled with it (it is not that useful anyway as Splash supports V4L2 natively). It should be updated in the latest master.
