### ISSUE TITLE
Object image filter inconsistently linked to the correct Image

### ISSUE THREAD

**Issue by charlesveasey** [paperManu/splash#48]
Splash Version 0.7.13
Branch: develop
OS: lubuntu 16.04 Alternate 64-bit

The `Object_Image_filter` is inconsistently linked to the correct `Image` when saved by the Splash GUI. A percentage of the time I had to switch the `Object` and `Object_Image_filter` next to the two `Image ` values in the JSON config file; otherwise, the image filter would not effect the texture. The JSON as saved by GUI:

```
      "links" : [
         [ "Camera", "Window_Camera_warp" ],
         [ "Image", "Object_Image_filter" ],
         [ "Camera", "Window" ],
         [ "Window_Camera_warp", "Window" ],
         [ "Mesh", "Object" ],
         [ "Image", "Object" ],
         [ "Object", "gui" ],
         [ "Object", "Camera" ],
         [ "gui", "Gui window" ]
      ],

```

To reproduce:
1. Create a scene with a GUI Window in Blender and load with Splash.
2. Test the Image filter (this always works).
3. Switch to "Video4Linux" in the GUI.
4. Save the config file with the GUI.
5.  Reload the the config file with Splash.
6. Test the Image filter (fails about 50% of the time).
7. Switch the JSON to fix:

```
      "links" : [
         [ "Camera", "Window_Camera_warp" ],
         [ "Image", "Object" ],
         [ "Camera", "Window" ],
         [ "Window_Camera_warp", "Window" ],
         [ "Mesh", "Object" ],
         [ "Image", "Object_Image_filter" ],
         [ "Object", "gui" ],
         [ "Object", "Camera" ],
         [ "gui", "Gui window" ]
      ],

**Comment by paperManu** [comment]
Could you send me the base JSON file?
Also, what do you mean by "Test the Image filter" ?

**Comment by charlesveasey** [comment]
Here's the JSON file:
[splash-issue-48.tar.gz](https://github.com/paperManu/splash/files/1690341/splash-issue-48.tar.gz)

I mean adjusting any of the filter parameters such as "invertChannels" or "brightness".

**Comment by paperManu** [comment]
Do you also have the original file, before switching to V4l2? Also, was it exported from Blender?

**Comment by charlesveasey** [comment]
Here is the project. Yes, it was exported from Blender. Included are two JSON files, one exported from Blender and the other exported from Blender and then saved with the GUI. You should see that the Blender project's image filter works, the other doesn't.

[splash-issue-48-2.tar.gz](https://github.com/paperManu/splash/files/1690721/splash-issue-48-2.tar.gz)

**Comment by paperManu** [comment]
Indeed, the other one does not work. The problem is that in your second file, the "Object_Image_filter" object is not linked to "Object".
I don't really understand why it did not save it correctly for you. I tried it and this is what I get:
```
      "links" : [
         [ "Camera", "Window_Camera_warp" ],
         [ "Mesh", "Object" ],
         [ "Image", "Object" ],
         [ "Object_Image_filter", "Object" ],
         [ "Object", "gui" ],
         [ "gui", "Gui window" ],
         [ "Object", "Camera" ],
         [ "Camera", "Window" ],
         [ "Window_Camera_warp", "Window" ],
         [ "Image", "Object_Image_filter" ]
      ],
```
Did you do anything beside setting the input to V4L2? Did you enable the capture?

**Comment by charlesveasey** [comment]
Yes, I changed the `captureSize`, enabled `doCapture`, and then saved.

How can one tell the difference between the two image links?

`[ "Image", "Object_Image_filter" ]`
and
`[ "Image", "Object" ]`

**Comment by paperManu** [comment]
Hi Charles,
I tested this with the latest commit from the develop branch, and I can't seem to reproduce the issue. If you have the time, could you confirm that it does not happen anymore?

**Comment by charlesveasey** [comment]
OK. I can't seem to reproduce it anymore.
