### ISSUE TITLE
Unable to install spash in ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by arunlee** [paperManu/splash#5]
Hi,

I updated my ubuntu to 14.04 and am trying to install splash, but it seems not working.

> sudo apt-add-repository ppa:andrewrk/rucksack
> sudo apt-add-repository ppa:thomas-schiex/blender

The above two commands did not work ( i am behind proxy) and i had to add the info manually in the apt sources..

Error:
aravind2@aravind2-HP-Compaq-8100-Elite:/etc/apt$ sudo apt-add-repository ppa:andrewrk/rucksack
Cannot add PPA: 'ppa:andrewrk/rucksack'.
Please check that the PPA name or format is correct.

> sudo sh -c 'echo "deb http://ppa.launchpad.net/sat-metalab/metalab/ubuntu trusty main" > /etc/apt/sources.list.d/sat-metalab-metalab-trusty.list'
> sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 27D9A33279DF04BB

The above commands fail at the key update, as

Error:
aravind2@aravind2-HP-Compaq-8100-Elite:/etc/apt$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 27D9A33279DF04BB
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.lWlP3nYY7j --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver keyserver.ubuntu.com --recv-keys 27D9A33279DF04BB
gpg: requesting key 79DF04BB from hkp server keyserver.ubuntu.com
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error

Could you please help me out?

regards
Arun

**Comment by paperManu** [comment]
Hi arunlee,

Well it seems like you had some connection timeouts, maybe because of your proxy. I tried all of them from my place and they worked flawlessly.

You have to choice: try to configure your proxy so that it works (or ask your admin to do so), or add the repository yourself to /etc/apt/sources.list or /etc/apt/sources.list.d.

**Comment by arunlee** [comment]
Hi,

Looks like it was an issue came from the update i did when i moved to 14.04 LTS.
I did a sudo apt-get autoremove and then i could install the packaged version of splash with
sudo apt-get install splash. It installed a big chunk of the dependent libs.

But i still have other issues with splash, but i think i will open a new thread for that.
Thanks for the help any way.

regards
Arun
