### ISSUE TITLE
Not able to build (ArchLinux)

### ISSUE THREAD

**Issue by Yinameah** [paperManu/splash#50]
Hello,

I'm giving a hard try to compile splash on my archlinux system.

I'm stuck at the end of the build process with this (very long) error message below.

I'm not very experimented in build processes nor C programing, and I cannot understand what's this about. I may have done something wrong or miss a dependency (the conversion from Ubuntu and Archlinux packages names is not always trivial) but I spend some time on it and I cant' figure what.

Eternal respect to anyone how can help me.

`[ 98%] Built target unitTests
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-ctx.o) : Dans la fonction « zmq::ctx_t::ctx_t() » :
(.text+0x7251) : référence indéfinie vers « sodium_init »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-ctx.o) : Dans la fonction « zmq::ctx_t::~ctx_t() » :
(.text+0x7943) : référence indéfinie vers « randombytes_close »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-zmq.o) : Dans la fonction « zmq_ctx_new » :
(.text+0xa3) : référence indéfinie vers « pgm_init »
(.text+0x1f2) : référence indéfinie vers « pgm_error_free »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-zmq.o) : Dans la fonction « zmq_ctx_term » :
(.text+0x282) : référence indéfinie vers « pgm_shutdown »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-socket_base.o) : Dans la fonction « zmq::socket_base_t::connect(char const*) » :
(.text+0x5ba4) : référence indéfinie vers « pgm_freeaddrinfo »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-zmq_utils.o) : Dans la fonction « zmq_curve_keypair » :
(.text+0x370) : référence indéfinie vers « crypto_box_keypair »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-zmq_utils.o) : Dans la fonction « zmq_curve_public » :
(.text+0x3f8) : référence indéfinie vers « crypto_scalarmult_base »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-pgm_socket.o) : Dans la fonction « zmq::pgm_socket_t::init_address(char const*, pgm_addrinfo_t**, unsigned short*) » :
(.text+0x182) : référence indéfinie vers « pgm_getaddrinfo »
(.text+0x27b) : référence indéfinie vers « pgm_error_free »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-pgm_socket.o) : Dans la fonction « zmq::pgm_socket_t::get_receiver_fds(int*, int*) » :
(.text+0x2f7) : référence indéfinie vers « pgm_getsockopt »
(.text+0x32b) : référence indéfinie vers « pgm_getsockopt »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-pgm_socket.o) : Dans la fonction « zmq::pgm_socket_t::get_sender_fds(int*, int*, int*, int*) » :
(.text+0x5e3) : référence indéfinie vers « pgm_getsockopt »
(.text+0x617) : référence indéfinie vers « pgm_getsockopt »
(.text+0x64b) : référence indéfinie vers « pgm_getsockopt »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-pgm_socket.o):(.text+0x67f) : encore plus de références indéfinies suivent vers « pgm_getsockopt »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-pgm_socket.o) : Dans la fonction « zmq::pgm_socket_t::send(unsigned char*, unsigned long) » :
(.text+0xb00) : référence indéfinie vers « pgm_send »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-pgm_socket.o) : Dans la fonction « zmq::pgm_socket_t::get_rx_timeout() » :
(.text+0xced) : référence indéfinie vers « pgm_getsockopt »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-pgm_socket.o) : Dans la fonction « zmq::pgm_socket_t::get_tx_timeout() » :
(.text+0xde2) : référence indéfinie vers « pgm_getsockopt »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-pgm_socket.o) : Dans la fonction « zmq::pgm_socket_t::get_max_tsdu_size() » :
(.text+0xeca) : référence indéfinie vers « pgm_getsockopt »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-pgm_socket.o) : Dans la fonction « zmq::pgm_socket_t::init(bool, char const*) » :
(.text+0x107b) : référence indéfinie vers « pgm_socket »
(.text+0x1125) : référence indéfinie vers « pgm_setsockopt »
(.text+0x1149) : référence indéfinie vers « pgm_setsockopt »
(.text+0x118f) : référence indéfinie vers « pgm_setsockopt »
(.text+0x11c2) : référence indéfinie vers « pgm_setsockopt »
(.text+0x126a) : référence indéfinie vers « pgm_setsockopt »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-pgm_socket.o):(.text+0x1290) : encore plus de références indéfinies suivent vers « pgm_setsockopt »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-pgm_socket.o) : Dans la fonction « zmq::pgm_socket_t::init(bool, char const*) » :
(.text+0x13fe) : référence indéfinie vers « pgm_gsi_create_from_data »
(.text+0x144f) : référence indéfinie vers « pgm_bind3 »
(.text+0x1522) : référence indéfinie vers « pgm_setsockopt »
(.text+0x1536) : référence indéfinie vers « pgm_close »
(.text+0x154d) : référence indéfinie vers « pgm_freeaddrinfo »
(.text+0x1566) : référence indéfinie vers « pgm_error_free »
(.text+0x15b7) : référence indéfinie vers « pgm_socket »
(.text+0x16d5) : référence indéfinie vers « pgm_setsockopt »
(.text+0x1703) : référence indéfinie vers « pgm_setsockopt »
(.text+0x172c) : référence indéfinie vers « pgm_setsockopt »
(.text+0x1750) : référence indéfinie vers « pgm_setsockopt »
(.text+0x178f) : référence indéfinie vers « pgm_setsockopt »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-pgm_socket.o):(.text+0x17c1) : encore plus de références indéfinies suivent vers « pgm_setsockopt »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-pgm_socket.o) : Dans la fonction « zmq::pgm_socket_t::init(bool, char const*) » :
(.text+0x17d4) : référence indéfinie vers « pgm_freeaddrinfo »
(.text+0x1803) : référence indéfinie vers « pgm_setsockopt »
(.text+0x1831) : référence indéfinie vers « pgm_setsockopt »
(.text+0x186c) : référence indéfinie vers « pgm_setsockopt »
(.text+0x1880) : référence indéfinie vers « pgm_connect »
(.text+0x18b7) : référence indéfinie vers « pgm_setsockopt »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-pgm_socket.o) : Dans la fonction « zmq::pgm_socket_t::receive(void**, pgm_tsi_t const**) » :
(.text+0x1d74) : référence indéfinie vers « pgm_recvmsgv »
(.text+0x2059) : référence indéfinie vers « pgm_free »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-pgm_socket.o) : Dans la fonction « zmq::pgm_socket_t::process_upstream() » :
(.text+0x233c) : référence indéfinie vers « pgm_recvmsgv »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-pgm_socket.o) : Dans la fonction « zmq::pgm_socket_t::~pgm_socket_t() » :
(.text+0x24a8) : référence indéfinie vers « pgm_close »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-curve_client.o) : Dans la fonction « zmq::curve_client_t::encode(zmq::msg_t*) » :
(.text+0x19d) : référence indéfinie vers « crypto_box_afternm »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-curve_client.o) : Dans la fonction « zmq::curve_client_t::decode(zmq::msg_t*) » :
(.text+0x553) : référence indéfinie vers « crypto_box_open_afternm »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-curve_client.o) : Dans la fonction « zmq::curve_client_t::curve_client_t(zmq::options_t const&) » :
(.text+0x896) : référence indéfinie vers « crypto_box_keypair »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-curve_client.o) : Dans la fonction « zmq::curve_client_t::produce_hello(zmq::msg_t*) » :
(.text+0x9d2) : référence indéfinie vers « crypto_box »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-curve_client.o) : Dans la fonction « zmq::curve_client_t::process_welcome(unsigned char const*, unsigned long) » :
(.text+0xc03) : référence indéfinie vers « crypto_box_open »
(.text+0xc8a) : référence indéfinie vers « crypto_box_beforenm »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-curve_client.o) : Dans la fonction « zmq::curve_client_t::produce_initiate(zmq::msg_t*) » :
(.text+0xddd) : référence indéfinie vers « randombytes »
(.text+0xdfb) : référence indéfinie vers « crypto_box »
(.text+0xf72) : référence indéfinie vers « crypto_box »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-curve_client.o) : Dans la fonction « zmq::curve_client_t::process_ready(unsigned char const*, unsigned long) » :
(.text+0x11de) : référence indéfinie vers « crypto_box_open_afternm »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-curve_server.o) : Dans la fonction « zmq::curve_server_t::encode(zmq::msg_t*) » :
(.text+0x1cf) : référence indéfinie vers « crypto_box_afternm »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-curve_server.o) : Dans la fonction « zmq::curve_server_t::decode(zmq::msg_t*) » :
(.text+0x584) : référence indéfinie vers « crypto_box_open_afternm »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-curve_server.o) : Dans la fonction « zmq::curve_server_t::curve_server_t(zmq::session_base_t*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, zmq::options_t const&) » :
(.text+0x99c) : référence indéfinie vers « crypto_box_keypair »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-curve_server.o) : Dans la fonction « zmq::curve_server_t::process_hello(zmq::msg_t*) » :
(.text+0xc0f) : référence indéfinie vers « crypto_box_open »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-curve_server.o) : Dans la fonction « zmq::curve_server_t::produce_welcome(zmq::msg_t*) » :
(.text+0xd0e) : référence indéfinie vers « randombytes »
(.text+0xd72) : référence indéfinie vers « randombytes »
(.text+0xd8b) : référence indéfinie vers « crypto_secretbox »
(.text+0xdb7) : référence indéfinie vers « randombytes »
(.text+0xe5b) : référence indéfinie vers « crypto_box »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-curve_server.o) : Dans la fonction « zmq::curve_server_t::produce_ready(zmq::msg_t*) » :
(.text+0x10f2) : référence indéfinie vers « crypto_box_afternm »
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/libzmq.a(src_libzmq_la-curve_server.o) : Dans la fonction « zmq::curve_server_t::process_initiate(zmq::msg_t*) » :
(.text+0x2299) : référence indéfinie vers « crypto_secretbox_open »
(.text+0x23c6) : référence indéfinie vers « crypto_box_open »
(.text+0x2466) : référence indéfinie vers « crypto_box_open »
(.text+0x24b6) : référence indéfinie vers « crypto_box_beforenm »
collect2: error: ld a retourné le statut de sortie 1
make[2]: *** [src/CMakeFiles/splash.dir/build.make:106: src/splash] Error 1
make[1]: *** [CMakeFiles/Makefile2:503: src/CMakeFiles/splash.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
`

**Comment by paperManu** [comment]
Hello Yinameah,
I'm completely new to Archlinux, could you tell me which packages you had to install to make Splash (almost) build?

**Comment by paperManu** [comment]
Yinameah,
The issue is with ZMQ, which when built on Archlinux seems to need libsodium even though it shouldn't. There was another issue: the pkg-config file for ZMQ was not generated correctly.
So, if you could try the checkout out and build the branch `fix/archlinux_build`, and tell me how it goes, it would be great. Don't forget to rebuild the dependencies too!

**Comment by Yinameah** [comment]
Hello,

Thank you so much for your fast answer.

I tried to checkout on your `fix/archlinux_build` branch and it worked ! I was able to finish the build.
I will now try to reproduce this with a PKGBUILD (which is the standard way to package custom software on Archlinux) and then in a clean VM to double check dependecies and hopefully be able to submit it on the Arch User Repository (https://aur.archlinux.org/) so Splash will be available for Archlinux.
(I'm on Arch for a while now, but I've very few experience with that kind of digging, good exercice for me)
I'll keep you posted.

Also, can you tell me if the `-DCMAKE_INSTALL_LIBDIR=lib` you added makes sense for every build and will stay in your code in future releases or if I should provide it as a patch specially for Archlinux.

Thank again.

**Comment by paperManu** [comment]
Hi Yinameah,

Glad that the fix worked. I added Archlinux to my CI so I'll be warned if anything goes wrong again.
I'm very curious to see how you build the package for Archlinux. You can test everything in Docker, it will be faster to set up that a VM and give mostly the same results.

And yes, I'll keep the `-DCMAKE_INSTALL_LIBDIR=lib` option in ZMQ, as it does not break anything on Ubuntu-side (this is already the default).

Keep me updated about the packaging for Archlinux, I'll close this issue as it is solved, and merge the `fix/archlinux_build` branch into develop.
