### ISSUE TITLE
Packaging for Archlinux

### ISSUE THREAD

**Issue by Yinameah** [paperManu/splash#51]
Hello (again). I'm working on this PKGBUILD for Archlinux and I've an issue, or maybe more a question.

In the `make && make install` process, some libs (apparently Snappy) are installed and this conflicts with already installed version of Snappy.

Is there a specific reason for them to be there or could I exclude them from the package and relies on upstream binaries ? For what I can see, every file created by the build process is already provided by the distro package.

So unless it has specifically been patched, it should be fine I guess.

PS : the way to "package" in Archlinux is actually to write a bash script in some "standardized" way which perform the build process and create an archive that the package manager can install. It is recommended to never install to `/usr/local` since it should remain empty for experimentation. 
So for exemple `/usr/local/include/snappy.h` would go in `/usr/include/snappy.h` which is already used by the snappy package (https://www.archlinux.org/packages/extra/x86_64/snappy/)

**Comment by paperManu** [comment]
Hi Yinameah,
I see what the issue is. Snappy is built along Splash and linked statically against it, but the library and header files are installed nonetheless.
What I have to do is prevent Snappy from being installed. I'll check that.

**Comment by Yinameah** [comment]
Ok, so let me know. Because I can manually not include them into the package, but if it makes no sense to have them for other distribution, it's better to remove in the source.
It's more clean and will be easier to maintain from my point of view.

**Comment by paperManu** [comment]
It's done! You can get the updated version from the develop branch.
