### ISSUE TITLE
Blender export : error while exporting mesh with a shared memory type

### ISSUE THREAD

**Issue by dlan-fr** [paperManu/splash#52]
Hello,

When exporting a scene with a mesh of shared memory type, I have this error in splash blender export : 

`Splash Tree exporting error : No object have been selected for node Mesh`

The error seem to come from an incorrect validation of the mesh node in  splash/addons/blender/splash/nodes.py, I ended up modifying the validate function of the SplashMeshNode class so it always return True as a workaround. 

I tested it with splash 0.7.14 on linux mint 18.3

**Comment by paperManu** [comment]
Indeed! This has been fixed in the develop branch, should arrive on master in the coming days.
