### ISSUE TITLE
No Python Shmdata module

### ISSUE THREAD

**Issue by Isaacchenjie** [paperManu/splash#54]
OS: ubuntu 16.04 32bit
version: 0.7.18

I compile the sources, but there is nothing in /usr/local/lib/python3/dist-packages.

And another problem is that when I enable blender addon, it shows "cannot import name "multiarray"."

**Comment by paperManu** [comment]
Hi Isaacchenjie,

Regarding your first issue,  shmdata is not bundled with Splash but it is an external dependency. You can get the sources from [here](https://gitlab.com/sat-metalab/shmdata/tree/master). The documentation should be sufficient.

Regarding the second issue, you have to install python3-numpy:
```bash
sudo apt install python3-numpy
```

**Comment by Isaacchenjie** [comment]
Thank you for your replay!!!

For the second issue, I am sure that I have installed python3-numpy. Infact I just follow the step in Installation page to compile the sources. I can import numpy.core.multiarray, but cannot import multiarray directly. The problem occurred in "numpy/core/__init__.py, from . import multiarray". I've tried to reinstall numpy, but it doesn't help.

**Comment by Isaacchenjie** [comment]
Thank you so much! I download the latest version of Blender, and this issue has been solved.

There is another issue. The statements of method "portAudioCallback" in speaker.cpp and speaker.h are different. The type of parameter "framesPerBuffer" is unsigned long in .h file, but uint64_t in .cpp file. Since my OS is 32bit, they have different size.

I change uint64_t to unsigned long and successfully pass the compilation. But I am not sure if there would be any error at runtime.

**Comment by paperManu** [comment]
Indeed, it should also be unsigned long in the .cpp. Thanks for noticing, I'll fix this.
