### ISSUE TITLE
3 x projectors warping and blending in Linux

### ISSUE THREAD

**Issue by haider04** [paperManu/splash#57]
Hi,

I am trying to calibrate, warp and blend my 3 x BenQ projectors, projecting on a cylindrical screen, in Linux Ubuntu 16.04 LTS OS. After a lot of research, i came to know about Splash, with some hopes. 

Currently the projectors are fixed and overlapped with each other. And i want to display simulation results on full screen so that the simulation is projected as 1 seamless image on full cylindrical screen. 

I am confused about the working method of Splash. Will it project the images and videos of some specific formats only? 

I want something like, after i do projectors warping and blending, i can see full Linux desktop on the screen and i can then use it to play any simulation/game on full screen. Is this possible with Splash? 

Or what other options would you suggest? 

A prompt detailed reply is highly appreciated. Thanks! 

Haider

**Comment by haider04** [comment]
Just to add, i will be connecting 3 projectors to a single graphics card (Nvidia GeForce GTX 980). Each projector has a resolution of 1920 x 1080. So after blending, the combined image would be 5670 x 1080. 

Will the configuration work with Splash? And the main thing i am concerned about is the projection of simulation through a simulation software on full cylindrical screen.

**Comment by paperManu** [comment]
Hi haider04,
Yes, such a configuration would work with Splash. You should know that Splash does not know how to capture the desktop, so you have two choices:
- build a separate computer with a capture card, and connect your simulation computer to the Splash computer through this card. This is known to work well, albeit adding a few ms lag to the video output.
- manage to capture a XScreen and send it to Video4Linux or Shmdata, for example using VirtualGL. It is something I wanted to try but never had the time.
Also, you have to make sure that your simulation software knows how to render a cylindrical projection, or this wouldn't make much sense projecting it onto a cylindrical screen.

**Comment by paperManu** [comment]
Haider,

To be a bit more precise, Splash is able to map an input video texture onto a physical object, given its 3D model and texture coordinates.
So on your simulation software side, you have to make it output an immersive rendering (spherical, equirectangular, or cubemap for example). Then you have to create a 3D model of your physical screen (a cylinder in your case), with the right texture coordinates to map correctly the immersive rendering onto the screen.

To sum things up:
* your software renders an immersive rendering
* you create a 3D model of the physical screen with the correct texture coordinates
* this 3D model is given to Splash, which then is used to do the calibration of the projectors
* finally, Splash reads the immersive rendering from your simulation software and projects it onto the screen.

As far as I understand, what you could do in your software:
* make it render to spherical / equirectangular / cubemap (pick one)
* make it output the rendered frames to shmdata (https://gitlab.com/sat-metalab/shmdata), or you video4linux using v4l2loopback (https://github.com/umlaeute/v4l2loopback)

The main issue would be the latency added by the necessity to download the frames from the GPU to the CPU (in your software), then upload them back from the CPU to the GPU (in Splash). But it should work nonetheless.

I hope this helps!

**Comment by paperManu** [comment]
Haider,

How are things going on your side? Do you need any more help?

**Comment by marcin-koziol-iteo** [comment]
>     * manage to capture a XScreen and send it to Video4Linux or Shmdata, for example using VirtualGL. It is something I wanted to try but never had the time.

Is it possible to use Xvfb's framebuffer directly as a video stream for splash?

**Comment by paperManu** [comment]
Hello marcin-koziol-iteo,
It should be possible if you manage to grab the Xvfb framebuffer. Maybe `ffmpeg` can do it through the `x11grab` object as input, and `v4l2` object as output. Splash could then read the `v4l2` virtual device. I have not tested this though.
If you manage to make this work please tell me how you did it!

**Comment by marcin-koziol-iteo** [comment]
Xvfb is able to create mempry mapped files with current screen content. It is possible to "view" this content live, using vlc and shm:// protocol (I've tested xvfb + virtualGL solution). I have to map 4k output from openglapp using 4 projectors, so putting video memory to v4l2 loopback looks like a waste of resources. If splash is not able to consume this shm, I'll try to play with VLC's code and use it in splash. I think that option with using any application as a video source would be a nice addition.

**Comment by paperManu** [comment]
Oh nice, I'm very interested in your setup and how you used xvfb + VirtualGL.
If VLC is able to read the result from the shared memory, it should not be a lot of work to implement it in Splash. In fact Splash already supports shared memory through a lib named shmdata, but it certainly is not compatible. This could serve as a useful basis to build upon though.
Would you mind sharing your xvfb + VirtualGL setup? Also, maybe we can continue this exchange by email if you don't mind, here is mine: edurand @ sat.qc.ca
