### ISSUE TITLE
Image (object) alias change causes texture crash when switching media source

### ISSUE THREAD

**Issue by efram-emersi** [paperManu/splash#59]
If the Image object in the config file has been given a different alias (e.g. Image.1), Splash's texture mapper crashes upon switching media sources. It was also unable to play video or use capture card when setting the media type in the config directly. Issue was resolved when the alias was changed back to "Image"

**Comment by paperManu** [comment]
Hello efram-emersi,
I was not able to reproduce the issue from your description. Could you send a configuration file which shows the issue, and a step-by-step guide to reproduce it?
Thanks!

**Comment by charlesveasey** [comment]
It's only an issue with multiple GPUs or scenes.
[DMNS_Blender.zip](https://github.com/paperManu/splash/files/2271162/DMNS_Blender.zip)

**Comment by paperManu** [comment]
I loaded the configuration in my current development branch and did not see any issue regarding switching the media source.
Could you please send me a copy of the logs, including the Splash version number?

**Comment by paperManu** [comment]
Any news about thie @efram-emersi ?

**Comment by efram-emersi** [comment]
Sorry for the wait, Manu. I completely forgot to close this. The issue was resolved when we switched over to the development branch. We were originally in the Master. Thanks for looking into this and sorry for the time you spent on it!
