### ISSUE TITLE
Typical Configuration to test splash

### ISSUE THREAD

**Issue by arunlee** [paperManu/splash#6]
Hi,

I am trying to use splash to learn more about it. I am a newbie trying to learn as i go :-)
What is the hardware configuration you are using to test splash?
How do i integrate projectors (i have couple of TI Pico projectors) to use splash?

regards
Arun

**Comment by paperManu** [comment]
Hi again,

Did you check the [Wiki](https://github.com/paperManu/splash/wiki)? Especially the Walkthrough page?
I know it is not perfect but there should already be a lot of information in there.

Regarding the configuration, I would recommend at least a Core i5 as a CPU, and a dedicated GPU. It does work with the Intel integrated GPUs but the performances are not ideal.

Also, don't hesitate to come ask questions on [Freenode, channel ##splash](http://webchat.freenode.net/?randomnick=1&channels=%23%23splash&uio=d4).

**Comment by arunlee** [comment]
Hi,

I didn't quite understand the HW setup. The wiki though says splash can be used to project using multiple projectors, but is not mentioning about what is the HW configuration. Are the projectors using HDMI inputs, or a display port etc...

I am trying to use a pico projector (with an HDMI input) to project to a curved surface, and wants to see how can i use splash for that. I am using an Intel Core i7 with a Gallium 0.4 on NVA8, running ubuntu 14.04. When i try the packaged version of splash, it usually makes my PC hang or there is a crash as

                 - Splash -
    - Modular multi-output video mapper -
              - Version 0.1.8 -

18:18:33 / [MESSAGE] / splashScene::main - Creating Scene with name local
18:18:34 / [MESSAGE] / Camera::Camera - Framebuffer object successfully initialized
18:18:34 / [MESSAGE] / Camera::Camera - Camera correctly initialized
18:18:34 / [MESSAGE] / Gui::Gui - Framebuffer object successfully initialized
18:18:34 / [MESSAGE] / Camera::Camera - Framebuffer object successfully initialized
18:18:34 / [MESSAGE] / Camera::Camera - Camera correctly initialized
18:18:34 / [MESSAGE] / Window::Window - Window created successfully
18:18:34 / [WARNING] / Shader::linkProgram - Error while linking the shader program
18:18:34 / [WARNING] / Shader::linkProgram - Error log: 
error: vertex shader output `position' specifies smooth interpolation qualifier, but fragment shader input specifies no interpolation qualifier
error: vertex shader output `texCoord' specifies smooth interpolation qualifier, but fragment shader input specifies no interpolation qualifier
error: vertex shader output `normal' specifies smooth interpolation qualifier, but fragment shader input specifies no interpolation qualifier

/usr/bin/splash-scene: symbol lookup error: /usr/lib/libsplash-0.1.so.0: undefined symbol: _ZN11OpenImageIO4v1_310ParamValue12init_noclearENS0_7ustringENS0_8TypeDescEiNS1_6InterpEPKvb


I am trying to compile now. But i am kind of lost with the overall setup, the projectors etc.

Could you please guide me?

regards
Arun

**Comment by paperManu** [comment]
Before anything, it looks like you have compiled a very old version of Splash. Your post says you are using version 0.1.8, although the current version is 0.3.8. You should do the following:

```
git checkout master
git pull origin master
```

And then follow again the README.md to compile and install Splash. This should solve the shader error you have, as I have solved it a long time ago (this error is specific to the Intel GPUs as far as I know).

Regarding the hardware setup, it really is up to you. As long as the projectors are correctly configured so that your OS can output to it, it should be ready to use. So the kind of connection (HDMI, DVI...) does not matter at all.

**Comment by arunlee** [comment]
Hi Again,

Today i could compile splash. but while running i have a crash...

aravind2@aravind2-HP-Compaq-8100-Elite:~/splash/splash/data$ splash -d -o config.json
ALSA lib pcm_dsnoop.c:584:(snd_pcm_dsnoop_open) unable to create IPC semaphore
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
14:58:34 / [MESSAGE] / Listener::initResources - Connected to device: default
14:58:34 / [MESSAGE] / Listener::initResources - Successfully opened PortAudio stream

                 - Splash -
    - Modular multi-output video mapper -
              - Version 0.3.9 -

14:58:34 / [MESSAGE] / World::applyConfig - Starting an inner Scene
14:58:34 /  [DEBUG]  / Scene::Scene - Scene created successfully
14:58:34 / [WARNING] / Link::Link::handleInputBuffershandleInputMessages - Exception:  - Exception: Address already in use
14:58:34 / [MESSAGE] / Address already in use
14:58:34 / [WARNING] / Scene::glfwErrorCallback - GLX: Failed to create context: GLXBadFBConfig
14:58:34 / [MESSAGE] / Scene::init - GL version: 3.3
14:58:38 /  [ERROR]  / World::applyConfig - Timeout when trying to connect to newly spawned scene "local". Exiting.

regards
Arun

**Comment by paperManu** [comment]
This line says that the interprocess communication could not be started:
```
14:58:34 / [WARNING] / Link::Link::handleInputBuffershandleInputMessages - Exception: - Exception: Address already in use
```

Can you make sure before running Splash that there is no file with the name starting with "splash_" in /tmp/? Do something like this:

```
rm -rf /tmp/splash_*
```

**Comment by arunlee** [comment]
Hi Again,

I get segmentation fault....

tried with gdb, and the out put is....

aravind2@aravind2-HP-Compaq-8100-Elite:~/splash/splash/data$ gdb splash
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from splash...done.
(gdb) r -d -o config.json
Starting program: /usr/local/bin/splash -d -o config.json
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe701a700 (LWP 8944)]
[New Thread 0x7fffe6819700 (LWP 8945)]
[New Thread 0x7fffe6018700 (LWP 8946)]
[New Thread 0x7fffe5817700 (LWP 8947)]
[New Thread 0x7fffe5016700 (LWP 8948)]
[New Thread 0x7fffe4815700 (LWP 8949)]
[New Thread 0x7fffe4014700 (LWP 8950)]
[New Thread 0x7fffe3813700 (LWP 8951)]
ALSA lib pcm_dsnoop.c:584:(snd_pcm_dsnoop_open) unable to create IPC semaphore
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
[New Thread 0x7fffdd008700 (LWP 8952)]
[Thread 0x7fffdd008700 (LWP 8952) exited]
[New Thread 0x7fffdd008700 (LWP 8953)]
[Thread 0x7fffdd008700 (LWP 8953) exited]
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
[New Thread 0x7fffdd008700 (LWP 8954)]
[Thread 0x7fffdd008700 (LWP 8954) exited]
[New Thread 0x7fffdd008700 (LWP 8955)]
[Thread 0x7fffdd008700 (LWP 8955) exited]
[New Thread 0x7fffdd008700 (LWP 8960)]
[Thread 0x7fffdd008700 (LWP 8960) exited]
09:50:48 / [MESSAGE] / Listener::initResources - Connected to device: default
[New Thread 0x7fffdd008700 (LWP 8961)]
[New Thread 0x7fffe0dda700 (LWP 8962)]
09:50:48 / [MESSAGE] / Listener::initResources - Successfully opened PortAudio stream
[New Thread 0x7fffe05d9700 (LWP 8963)]

                 - Splash -
    - Modular multi-output video mapper -
              - Version 0.3.9 -

[New Thread 0x7fffdfdd8700 (LWP 8964)]
[New Thread 0x7fffdf5d7700 (LWP 8965)]
[New Thread 0x7fffdedd6700 (LWP 8966)]
[New Thread 0x7fffde5d5700 (LWP 8967)]
[New Thread 0x7fffdddd4700 (LWP 8968)]
09:50:48 / [MESSAGE] / World::applyConfig - Starting an inner Scene
09:50:48 /  [DEBUG]  / Scene::Scene - Scene created successfully
09:50:48 / [WARNING] / Scene::glfwErrorCallback - GLX: Failed to create context: GLXBadFBConfig
09:50:48 / [MESSAGE] / Scene::init - GL version: 3.3
[New Thread 0x7fffd11d9700 (LWP 8969)]
[New Thread 0x7fffd09d8700 (LWP 8970)]
[New Thread 0x7fffbbfff700 (LWP 8971)]
[New Thread 0x7fffbb7fe700 (LWP 8972)]
[New Thread 0x7fffbaffd700 (LWP 8973)]
[New Thread 0x7fffba7fc700 (LWP 8974)]
[New Thread 0x7fffb9ffb700 (LWP 8975)]
[New Thread 0x7fffb97fa700 (LWP 8976)]
09:50:48 / [MESSAGE] / Gui::Gui - Framebuffer object successfully initialized
09:50:48 / [MESSAGE] / Camera::init - Framebuffer object successfully initialized
09:50:48 / [MESSAGE] / Camera::init - Camera correctly initialized
09:50:48 /  [DEBUG]  / Scene::add - Creating object of type camera
09:50:48 / [MESSAGE] / Camera::init - Framebuffer object successfully initialized
09:50:48 / [MESSAGE] / Camera::init - Camera correctly initialized
09:50:48 /  [DEBUG]  / Scene::add - Creating object of type camera
09:50:48 / [MESSAGE] / Camera::init - Framebuffer object successfully initialized
09:50:48 / [MESSAGE] / Camera::init - Camera correctly initialized
09:50:48 /  [DEBUG]  / Scene::add - Creating object of type geometry
09:50:48 /  [DEBUG]  / Scene::add - Creating object of type gui
09:50:48 /  [DEBUG]  / Scene::add - Creating object of type image
09:50:48 /  [DEBUG]  / Scene::add - Creating object of type mesh
09:50:49 /  [DEBUG]  / Scene::add - Creating object of type object
09:50:49 /  [DEBUG]  / Scene::add - Creating object of type texture
09:50:49 /  [DEBUG]  / Scene::add - Creating object of type window
09:50:49 / [MESSAGE] / Window::Window - Window created successfully
09:50:49 / [MESSAGE] / Window::Window - Render framebuffer object successfully initialized
09:50:49 / [MESSAGE] / Window::setupReadFBO - Read framebuffer object successfully initialized
09:50:49 / [MESSAGE] / Window::setupReadFBO - Read framebuffer object successfully initialized
09:50:49 /  [DEBUG]  / Scene::add - Creating object of type window
09:50:49 / [MESSAGE] / Window::Window - Window created successfully
09:50:49 / [MESSAGE] / Window::Window - Render framebuffer object successfully initialized
09:50:49 / [MESSAGE] / Window::setupReadFBO - Read framebuffer object successfully initialized

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb97fa700 (LWP 8976)]
0x00007fffd3c02e87 in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so


regards
Arun

**Comment by paperManu** [comment]
Hi Arunlee,

Thanks for your patience, Splash was not tried yet on a wide range of hardware and it looks like yours is quite different from what I got. Hence the crashes.

This one definitely looks like a driver issue. Could you try again to run it in GDB, but before that compile it with debug informations, like this:
```
cd ~/splash/splash
make clean
CXXFLAGS='-g3 -O0' ./configure
make && sudo make install
gdb splash
```

Running Splash without arguments automatically uses config.json, which is copied into /usr/local/share/splash.
Run it and once it crashed, type this and give me the output:

```
backtrace full
```

**Comment by arunlee** [comment]
Hi Again,

Here the logs as requested...


aravind2@aravind2-HP-Compaq-8100-Elite:~/splash/splash$ gdb splash
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from splash...done.
(gdb) r
Starting program: /usr/local/bin/splash 
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe6a67700 (LWP 2772)]
[New Thread 0x7fffe6266700 (LWP 2773)]
[New Thread 0x7fffe5a65700 (LWP 2774)]
[New Thread 0x7fffe5264700 (LWP 2775)]
[New Thread 0x7fffe4a63700 (LWP 2776)]
[New Thread 0x7fffe4262700 (LWP 2777)]
[New Thread 0x7fffe3a61700 (LWP 2778)]
[New Thread 0x7fffe3260700 (LWP 2779)]
ALSA lib pcm_dsnoop.c:584:(snd_pcm_dsnoop_open) unable to create IPC semaphore
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
[New Thread 0x7fffdca55700 (LWP 2780)]
[Thread 0x7fffdca55700 (LWP 2780) exited]
[New Thread 0x7fffdca55700 (LWP 2781)]
[Thread 0x7fffdca55700 (LWP 2781) exited]
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
[New Thread 0x7fffdca55700 (LWP 2782)]
[Thread 0x7fffdca55700 (LWP 2782) exited]
[New Thread 0x7fffdca55700 (LWP 2783)]
[Thread 0x7fffdca55700 (LWP 2783) exited]
[New Thread 0x7fffdca55700 (LWP 2788)]
[Thread 0x7fffdca55700 (LWP 2788) exited]
13:55:56 / [MESSAGE] / Listener::initResources - Connected to device: default
[New Thread 0x7fffdca55700 (LWP 2789)]
[New Thread 0x7fffe0827700 (LWP 2790)]
13:55:56 / [MESSAGE] / Listener::initResources - Successfully opened PortAudio stream
[New Thread 0x7fffe0026700 (LWP 2791)]

	             - Splash -
	- Modular multi-output video mapper -
	          - Version 0.3.9 -

13:55:56 / [MESSAGE] / No filename specified, loading default file
[New Thread 0x7fffdf825700 (LWP 2792)]
[New Thread 0x7fffdf024700 (LWP 2793)]
[New Thread 0x7fffde823700 (LWP 2794)]
[New Thread 0x7fffde022700 (LWP 2795)]
[New Thread 0x7fffdd821700 (LWP 2796)]
13:55:56 / [MESSAGE] / World::applyConfig - Starting an inner Scene
13:55:57 / [WARNING] / Scene::glfwErrorCallback - GLX: Failed to create context: GLXBadFBConfig
13:55:57 / [MESSAGE] / Scene::init - GL version: 3.3
[New Thread 0x7fffd0db7700 (LWP 2797)]
[New Thread 0x7fffbbfff700 (LWP 2798)]
[New Thread 0x7fffbb7fe700 (LWP 2799)]
[New Thread 0x7fffbaffd700 (LWP 2800)]
[New Thread 0x7fffba7fc700 (LWP 2801)]
[New Thread 0x7fffb9ffb700 (LWP 2802)]
[New Thread 0x7fffb97fa700 (LWP 2803)]
[New Thread 0x7fffb8ff9700 (LWP 2804)]
13:55:57 / [MESSAGE] / HttpServer::HttpServer - Http server opened at 127.0.0.1:9000
[New Thread 0x7fff9bfff700 (LWP 2805)]
[New Thread 0x7fff9b7fe700 (LWP 2806)]
13:55:57 / [MESSAGE] / Gui::Gui - Framebuffer object successfully initialized
13:55:57 / [MESSAGE] / Camera::init - Framebuffer object successfully initialized
13:55:57 / [MESSAGE] / Camera::init - Camera correctly initialized
13:55:57 / [MESSAGE] / Camera::init - Framebuffer object successfully initialized
13:55:57 / [MESSAGE] / Camera::init - Camera correctly initialized
13:55:57 / [WARNING] / Image_FFmpeg::read - Couldn't read file big_buck_bunny_1080p_stereo.avi
13:55:57 / [MESSAGE] / Window::Window - Window created successfully
13:55:57 / [MESSAGE] / Window::Window - Render framebuffer object successfully initialized
13:55:57 / [MESSAGE] / Window::setupReadFBO - Read framebuffer object successfully initialized
13:55:57 / [MESSAGE] / Filter::init - Framebuffer object successfully initialized
13:55:57 / [MESSAGE] / Filter::init - Filter correctly initialized
nouveau: kernel rejected pushbuf: Invalid argument
nouveau: ch0: krec 0 pushes 2 bufs 2 relocs 0
nouveau: ch0: buf 00000000 00000004 00000004 00000004 00000000
nouveau: ch0: buf 00000001 00000006 00000004 00000000 00000004
nouveau: kernel rejected pushbuf: Invalid argument
nouveau: ch0: krec 0 pushes 2 bufs 2 relocs 0
nouveau: ch0: buf 00000000 00000004 00000004 00000004 00000000

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb8ff9700 (LWP 2804)]
0x00007fffd2bbc6c3 in ?? () from /usr/lib/x86_64-linux-gnu/libdrm_nouveau.so.2
(gdb) backtrace full
#0  0x00007fffd2bbc6c3 in ?? () from /usr/lib/x86_64-linux-gnu/libdrm_nouveau.so.2
No symbol table info available.
#1  0x00007fffd2bbcf7c in ?? () from /usr/lib/x86_64-linux-gnu/libdrm_nouveau.so.2
No symbol table info available.
#2  0x00007fffd2bbcfbe in ?? () from /usr/lib/x86_64-linux-gnu/libdrm_nouveau.so.2
No symbol table info available.
#3  0x00007fffd2bbda70 in nouveau_pushbuf_kick () from /usr/lib/x86_64-linux-gnu/libdrm_nouveau.so.2
No symbol table info available.
#4  0x00007fffd38701ed in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
No symbol table info available.
#5  0x00007fffd36fa744 in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
No symbol table info available.
#6  0x00007fffd360818a in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
No symbol table info available.
#7  0x00007fffd3720da3 in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
No symbol table info available.
#8  0x00007fffd37d1d7f in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
No symbol table info available.
#9  0x00007fffd35e623d in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
No symbol table info available.
#10 0x00007fffece6f1b5 in glXMakeCurrentReadSGI () from /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
No symbol table info available.
#11 0x00007ffff3f5a6da in ?? () from /usr/lib/x86_64-linux-gnu/libglfw.so.3
No symbol table info available.
#12 0x00007ffff76fe4b9 in Splash::GlWindow::releaseContext (this=0x764838) at ../include/coretypes.h:163
No locals.
#13 0x00007ffff77f7210 in Splash::Window::swapBuffers (this=0xd969d8) at window.cpp:473
        windowIndex = 0
#14 0x00007ffff778a567 in Splash::Scene::render (this=0x672ee8) at scene.cpp:507
        __range = @0x672fe0: {_M_t = {
            _M_impl = {<std::allocator<std::_Rb_tree_node<std::pair<std::basic_string<char> const, std::shared_ptr<Splash::BaseObject> > > >> = {<__gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<std::basic_string<char> const, std::shared_ptr<Splash::BaseObject> > > >> = {<No data fields>}, <No data fields>}, 
              _M_key_compare = {<std::binary_function<std::basic_string<char>, std::basic_string<char>, bool>> = {<No data fields>}, <No data fields>}, _M_header = {_M_color = std::_S_red, 
                _M_parent = 0xcec4f0, _M_left = 0xc436f0, _M_right = 0xf66f00}, _M_node_count = 9}}}
        __begin = {_M_node = 0xf66f00}
        __end = {_M_node = 0x672fe8}
        obj = @0xf66f20: {first = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
              _M_p = 0xcac718 "win1"}}, second = {<std::__shared_ptr<Splash::BaseObject, 2>> = {_M_ptr = 0xd969d8, _M_refcount = {_M_pi = 0xd969c0}}, <No data fields>}}
        isError = false
        threadIds = {<std::_Vector_base<unsigned int, std::allocator<unsigned int> >> = {
            _M_impl = {<std::allocator<unsigned int>> = {<__gnu_cxx::new_allocator<unsigned int>> = {<No data fields>}, <No data fields>}, _M_start = 0x0, _M_finish = 0x0, 
              _M_end_of_storage = 0x0}}, <No data fields>}
        lock = {_M_device = 0x673230, _M_owns = false}
#15 0x00007ffff7783d49 in Splash::Scene::run (this=0x672ee8) at scene.cpp:535
        lock = {_M_device = @0x672f90}
#16 0x00007ffff7845257 in operator() (this=0x9a3230) at world.cpp:305
No locals.
#17 0x00007ffff7845205 in std::_Bind_simple<Splash::World::applyConfig()::$_1 ()>::_M_invoke<>(std::_Index_tuple<>) (this=0x9a3230)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:1731
No locals.
#18 0x00007ffff78451d5 in std::_Bind_simple<Splash::World::applyConfig()::$_1 ()>::operator()() (this=0x9a3230) at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:1720
No locals.
#19 0x00007ffff78451ac in std::thread::_Impl<std::_Bind_simple<Splash::World::applyConfig()::$_1 ()> >::_M_run() (this=0x9a3218)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/thread:115
No locals.
#20 0x00007ffff5740a40 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#21 0x00007ffff2d78182 in start_thread (arg=0x7fffb8ff9700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7fffb8ff9700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736297146112, 2594935883206374076, 1, 0, 140736297146816, 140736297146112, -2595092010131115332, -2594929076263963972}, mask_was_saved = 0}}, 
          priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
---Type <return> to continue, or q <return> to quit---
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#22 0x00007ffff4ea847d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.


Hope this helps

regards
Arun

**Comment by paperManu** [comment]
OK, well it crashes on an OpenGL context switching. I think your GPU is too old / not good enough.

From what I found your computer has the first revision of the Intel HD Graphics integrated GPU. Until recently Intel integrated GPUs were really not on par with the rest of the industry, especially regarding their capabilities. Making Splash work on such a limited GPU would be hard and anyway, it would really not work great.

What I would suggest is to put a Nvidia GPU in your computer. Any GPU from the GTX family should do, as Splash even works on a very old 9600M (albeit slowly).

regards

**Comment by arunlee** [comment]
Hi,

Ok. I need to fetch a new graphics  card.

I will close this issue and open a new one when i am ready.

Thank you so much for the amazing support.

regards
Arun
