### ISSUE TITLE
Support for v4l2 mmap

### ISSUE THREAD

**Issue by mklomp** [paperManu/splash#60]
Currently only user-pointer memory for v4l2 is implemented. I am trying to project a full desktop image (though ffmpeg or gstreamer icw v4l2loopback) into splash. Unfortunately v4l2loopback only supports mmap memory (and no user-pointer).

**Comment by paperManu** [comment]
Hi mklomp,
Indeed, I only implemented what is needed for capturing through hardware devices (webcam, capture cards), which mostly support user pointer and not mmap.
I'll look into adding support for it.

**Comment by mklomp** [comment]
Hi paperManu,

Thanks for the fast reply. I've been playing around myself a bit and am able to display my desktop though rtp and capture this in image_ffmpeg.cpp by whitelisting rtp. This triggered me that you might also consider removing your implementation of v4l2 support, and use ffmpeg for this. In that case you could provide all ffmpeg types (including x11grab or windows/mac equivalents).

**Comment by paperManu** [comment]
Hi mklomp,
Indeed I could extend the ImageFFmpeg class to enable everything that is supported natively by FFmpeg. If you already have something functional, I would be happy to have a look at it.
Also, I'll keep the ImageV4L2 class as it has its own specificities, such as a better support for Datapath capture cards.

**Comment by mklomp** [comment]
Hi Emmanuel,

I’ve attached the working RTP version. This suffices for now, but we would really love a better resolution though x11grab right away. To get this thing running:

$ ffmpeg -f x11grab -s 1920x1080 -r 50 -i :0.0 -sdp_file ~/stream.sdp -f rtp rtp://localhost:20000

You might need need to specify the whitelist as well (depending on ffmpeg version). You can then include the stream.sdp file in your home directory in the video settings. As you can see I also tried to get x11grab and v4l2 working in the ffmpeg class. The class opens the stream correctly (as can be seen by the correct detection of the format), but then it complains about not able to seek to an unknown time. For some reason this is no problem with the RTP solution. This is where I ‘got stuck’/’ran out of time’. If you have a quick fix for this, I would be happy to test this!

Best regards,

Martin

**Comment by paperManu** [comment]
Hi Martin,
Thanks for the information. ImageFFmpeg has never been designed to read anything but a video file, and it has a few optimization to read them as fast and fluidly as possible. Making it compatible with live streams might be quite a lot of work.
On the other hand, adding support for mmap to ImageV4L2 is really not that far, so I'll look into that.

**Comment by paperManu** [comment]
Hi Martin,
Support for mmap in V4L2 has been added and is available in the develop branch. It has been tested with v4l2loopback.
Please open a new issue if you have problems using it.
