### ISSUE TITLE
Unable to start splash

### ISSUE THREAD

**Issue by mklomp** [paperManu/splash#61]
After our initial working setup we can not get Splash up and running again. It hangs after:

```
2018-08-30T09:44:41 / [MESSAGE] / No filename specified, loading default file
2018-08-30T09:44:41 / [MESSAGE] / World::addScene - Starting an inner Scene
2018-08-30T09:44:41 / [MESSAGE] / Scene::init - GL version: 4.5
2018-08-30T09:44:41 / [MESSAGE] / Scene::init - NV max swap groups: 1 / barriers: 0
2018-08-30T09:44:41 / [MESSAGE] / Scene::getNewSharedWindow - Window Splash::Window couldn't join the NV swap group
2018-08-30T09:44:41 / [MESSAGE] / Scene::getNewSharedWindow - Window Splash::Window couldn't bind the NV swap barrier
```

We get no GUI and closing is not possible. We also tried it with our own setup file with the same results. also tried it on a fresh ubuntu and splash installation.

**Comment by paperManu** [comment]
Hi mklomp,
Could you send me your configuration file?

**Comment by mklomp** [comment]
[entree.tar.gz](https://github.com/paperManu/splash/files/2337233/entree.tar.gz)

Please find the configs attached. But this also happens when we do give a config to splash.

**Comment by paperManu** [comment]
Do you mean that this happens even when running Splash without a configuration splash?

If so, it looks like an issue with your system. Could you send a copy of the output for the following commands:
```bash
uname -a
glxinfo
dmesg
```

**Comment by mklomp** [comment]
We have onboard DP and HDMI, and an Nvidia P4000. For now we tried 2 screens on different ports. Same screens as we used before when it still worked ;). Output of the commands:

```
$ uname -a
Linux linux 4.15.0-33-generic #36~16.04.1-Ubuntu SMP Wed Aug 15 17:21:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
Find outputs of dmesg and glxinfo attached.

[dmesg.txt](https://github.com/paperManu/splash/files/2339026/dmesg.txt)
[glxinfo.txt](https://github.com/paperManu/splash/files/2339027/glxinfo.txt)

**Comment by paperManu** [comment]
I still don't get why Splash stopped working, but here is what you could try:
* update the Nvidia drivers to the latest:
  ```bash
  cd /tmp
  wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-  ubuntu1604_9.2.148-1_amd64.deb
  sudo apt install $(pwd)/cuda-repo-ubuntu1604_9.2.148-1_amd64.deb
  sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
  sudo apt update
  sudo apt install nvidia-396 nvidia-396-dev
  ```
  Then reboot and try running Splash again
* If it does not work, install another Ubuntu-based distribution. The window manager of Ubuntu has its quirks and these days I prefer running LXDE or XFCE. You can try installing [Lubuntu](https://lubuntu.net) instead of Ubuntu, this is what we use here.

**Comment by mklomp** [comment]
Tried both solutions, and a combination of the two. Unfortunately no luck. I did not mention it yet but I built splash from source. But same results with package.

**Comment by paperManu** [comment]
One thing which bugs me is that Splash says that your computer has 1 swap group, but no barrier, which to my knowledge should not happen.
Is your onboard video card activated, and connected to a screen?

**Comment by mklomp** [comment]
It seems to be a problem when connecting a monitor to the motherboard. So if I put all my monitors on the nvidia card works.
