### ISSUE TITLE
in your test

### ISSUE THREAD

**Issue by jiaju1993** [paperManu/splash#62]
you mentioned although nothing higher than 4096x4096@60Hz has been tested yet (well, we tested 6144x6144@60Hz but the drive throughput was not sufficient to sustain the video bitrate).

could you please tell the type of your video cards  and CPU  use ? and whether your dual video cards, you use sli?

**Comment by paperManu** [comment]
I'll add these kind of details in the documentation.
To answer your questions right now:
* At the time of writing this line, we used a Quadro K5000 with a Xeon 1620 v2. It has also been successfully tested on a i5 2500k with a GTX 670. The important thing here is the SSD throughput (at least 400MB/sec for 4096x4096@60Hz) and the GPU memory throughput (at least 100GB/sec, although no precise measure has been performed).
* SLI is of no use for Splash, but if you have Quadro cards you can try Mosaic mode. The best is to keep the GPU on separate X screens and let Splash create processes for each one of them.

**Comment by jiaju1993** [comment]
Thanks for your kindly reply, on more question, in http://projection-mapping.org/splash/, it said that splash also support mac, is that right?  or is there something like sython for ubuntu?

**Comment by paperManu** [comment]
Splash used to support OSX until approximately version 0.6.2. After that I switched to OpenGL 4.5 and OSX sadly does not support it, so currently there is no build for OSX.

**Comment by paperManu** [comment]
Lastly: do not hesitate to connect to the IRC channel for this kind of general questions, I'd be happy to answer them in real-time ;)

http://webchat.freenode.net/?randomnick=1&channels=%23%23splash&uio=d4
