### ISSUE TITLE
Single v. multi-GPU use in Ubtuntu 18.04

### ISSUE THREAD

**Issue by KevinCain** [paperManu/splash#64]
Does Splash require a unified display configuration _across all screens_, or can it map to two or more GPUs without contiguous screen setup?

If the answer is 'yes' (it does require a unified screen setup), for a six-projector setup at 1920x1080x30fps, would a single GPU like the Matrox C-680 6-head card be acceptable for Splash's playback, blend and warp load, assuming a capable M.2 SATA SSD to play the HapQ source?

I ask about the single-GPU setup since in my experience, distros including Ubuntu cannot configure a contiguous display that addresses more than one GPU.  I believe some have successfully used multiple nVidia Quadro cards to create a contiguous display setup.  Perhaps dual/multiple AMD GPUs are also possible, though I don't have any experience there.

Of course, if Splash doesn't need contiguous display mapping across multiple GPUs, that would be interesting, too.

Lastly, by chance could you point me to any details of a setup for a similar (6)x1080p projection setup?  For example, are there any similar setups using two Quadro M4000 cards?

Thanks a million @paperManu for all your effort on this framework!

**Comment by KevinCain** [comment]
If there happen to be known uses running Splash on dual GPUs  I'd love to know the details of the configuration, particularly for Ubuntu 16.04/18.04.  As above, I assume the two GPUs would need to be Quadros if nVidia.

**Comment by paperManu** [comment]
Hi KevinCain,

Splash can run on multiple GPU without a 'unified screen setup'. In fact, even with two Quadros and a Quadro Sync card, it is advised to run Splash with each card on a separate display for performance reasons.

I have already ran Splash on two GTX670 (with 8 projectors), and Splash also runs daily on a computer with two Quadro K5200 with a Quadro Sync card. Anything faster than a GTX670 should run Splash flawlessly. The Matrox C-680 has, to my knowledge, a very limited memory bandwidth and won't run very well with Splash.

I also know that Splash has been successfully used on AMD gpus, with the open source Mesa driver. I have not tried it myself though.

**Comment by paperManu** [comment]
A Quadro M4000 should really have no issue running Splash on its 4 outputs. The only thing needed to use it is to set the outputs of the second GPU on a different Xscreen (in nvidia-settings). Usually, the latest nvidia drivers are go.

There is no example of such a setup, but you can start on the [walkthrough](https://github.com/paperManu/splash/wiki/Walkthrough) page to get an idea of how to create a configuration for Splash.

**Comment by KevinCain** [comment]
Thanks once again @paperManu, for a concise and practical reply.  I very much appreciate the direct experience!

A final question I should have included earlier:  what RAM guidelines would you advise?  Considering a < 10GB HapQ file, would 32GB of DDR4 RAM clocked @ 3000MHz be appropriate for dedicated Splash playback?

While I am heartened to hear that the Quadro M4000 cards should be sufficient, I am considering (2) RTX2070 GPUs, as this system may have additional uses in the future.  [Here's a comparison](https://gpu.userbenchmark.com/Compare/Nvidia-GTX-670-vs-Nvidia-RTX-2070/2181vs4029) using your dual GTX670 setup as a baseline.

From what you have said about your GTX670 setup, it seems that Ubuntu+Splash does not require workstation cards like Quadros, which is a distinct advantage.

It seems that getting multiple GPUs to work under Ubuntu 18.04 may require X Server display configurations to address all outputs properly (e.g., [this thread](https://askubuntu.com/questions/860428/dual-gpu-dual-monitor-second-monitor-black-with-a-shadow-of-the-mouse)).

If your experience favors one approach, I'm all ears, and thanks once again.

**Comment by paperManu** [comment]
RAM in Splash can be used as a cache for the decoded video frames. So the more the better, although 16GB is usually enough.

On the other hand, it is advised to store the films on a SSD. A standard SATA 3 SSD has enough bandwidth to be able to read a 4096 x 4096 @ 60Hz film, but this is the absolute maximum. If you need to go higher, you will need a faster device.

The RTX2070 should have absolutely no issue running Splash (at all) (you could maybe even run it multiple times on that ;). The only advantage of Quadro cards is the possibility to use a Quadro Sync card to synchronize all outputs, which may be important depending on the projected content.

Lastly, to get multiple GPUs to work under Ubuntu 18.04, you only need to set them up correctly in `nvidia-settings`. That's about it.

**Comment by KevinCain** [comment]
Thanks once again, I'm closing this issue now.

As you suggest, since the Turing family does not support NVLink, I think it's smarter to use the GTX-1080 card that supports NVLink and has a better track record under Ubuntu.  As you know, the Turing GPUs are mostly aimed at fast tensor math (TensorFlow, et cetera), anyhow, which doesn't help in this case.
