### ISSUE TITLE
Alpha matte (per projector)

### ISSUE THREAD

**Issue by KevinCain** [paperManu/splash#65]
Making a first tour of the Splash source, I haven’t found support for alpha mattes.  Naturally, I could be missing something.  What I hope to do is provide a matte per projector to mask the region of projection.  Is that a reasonable thing to do in Splash, or perhaps mattes are handled in another way?

**Comment by KevinCain** [comment]
Thanks, @paperManu -- you make a good point, but I've been unclear.

I'd like to use alpha mattes not for blending, but to mask specific regions in the scene.  That is, to define shapes in image-projector space for regions we don't want to project on. 

For instance, within the non-blend region of a given projector throw, we have a physical display mounted in the projection surface itself.   Therefore, we would like to ensure that the projection extends exactly up to, but not beyond, border of this physical display.  In CGI production, we might think of as a 'holdout' matte.

Ideally, this would be interactive to align the mattes with observed geometry.

Naturally these mattes could be incorporated in the source video, but that would entail trail and error as we do not precisely know where in actual space the source video will map until projection.  Being able to draw a bezier shape interactively would allow us to define the regions we want to exclude.

Does that make more sense?

**Comment by paperManu** [comment]
I see. In Splash you have to give a 3D model of the projection surface you will be using, so you 'naturally' crop around the projection surface borders.

If  you want to mask around a mobile shape, you can add to the configuration an object with no image, which will the be black. If you place in (in the 3D space) in front of the projection surface, it will have the same effect as a mask.

I hope this is clear, you may have to test Splash a bit more to figure out how to do this. If you have questions which need more immediate answers, you can try to contact me through IRC, on Freenode channel ##splash.

**Comment by KevinCain** [comment]
That makes perfect sense, @paperManu, thanks for this.  To briefly summarize my notes below, your suggested method using multiple 3D objects will work very well for me, thanks, provided that we have the option to both translate and scale the un-mapped objects in real time.

I do see how we could add models for each object physically mounted to the projection surface to our configuration as an un-mapped object, to achieve the holdout matte.  I realize that Splash has been using for dynamic scenes (quite wonderful!), so it seems we could dynamically translate these models during projection, to fine-tune the placement from the drawings to the actual space.

However, through my Splash inexperience it's not clear if we could also _dynamically scale these models_, again for fine-tuning as it will inevitably take several iterations to compensate for slight measurement errors by swapping in new edited 3D models.

It's this 'tuning loop' that made me suggest a holdout matte in image space, defined after calibration with bezier/NURBs curves.  In that way, the final mapping to the surface is known, so we can define the mattes once in that 'pixel-addressable space'.

Thanks once again!

**Comment by paperManu** [comment]
You can indeed dynamically scale, rotate and translate these models.

If you follow the walkthrough, you will also see that you can use Blender to feed in realtime a 3D model to Splash through shared memory. This needs a bit more setup though, so you should first try Splash with a simpler configuration.

**Comment by KevinCain** [comment]
Thank you for confirming, that's a beautiful approach.  I'll have a look at most the 'static' approach with given models and the more nimble realtime stream from Blender.

This is potentially a much better solution than drawing an alpha matte in projector space, and leads in many interesting directions; thanks for all your help and remedial explanations for things I should have been able to manage on my own.  ;-)

Hopefully the geometry overhead for the different 3D objects is negligible, too!
