### ISSUE TITLE
'Screen' selection in Window node

### ISSUE THREAD

**Issue by KevinCain** [paperManu/splash#67]
In the [walkthrough documentation](https://github.com/paperManu/splash/wiki/Walkthrough#general-information-about-calibration) for the single projector example and in the [UI notes](https://github.com/paperManu/splash/wiki/User_Interface#blender_export), a 'screen' term is shown in the Window node:
![single_proj_window](https://user-images.githubusercontent.com/5424003/51791897-146fed00-215f-11e9-8eae-3aff7f7e1d73.jpeg)
In the multi-projector example in the walkthrough, this 'screen' term is missing:
![multi_proj_window](https://user-images.githubusercontent.com/5424003/51791901-25206300-215f-11e9-8c2b-0bc047d87d79.jpeg)

The latter (no screen term) is what I see when I add a Window node in Blender 2.79b, running the Splash 0.7.12 add-on packaged with the [Debian Splash releases](https://github.com/paperManu/splash/releases) on Ubuntu 18.04.

Here's a single-projector example:
![splash_single_projector](https://user-images.githubusercontent.com/5424003/51791914-4ed98a00-215f-11e9-8e52-48a6e44c2d49.jpeg)

When loading this configuration in Splash, Splash draws the UI and projector output on the same screen 0.  I've configured two projectors as screen 1 via 'nvidia-settings' as root:
![x_server_settings](https://user-images.githubusercontent.com/5424003/51791958-da531b00-215f-11e9-930d-2ed45387b8fb.jpeg)

My questions, then:
- Should I see, and set, the 'screen' term in the Window node?  Or is this a legacy term? 
- Either way, how do I properly map the Window nodes to the projectors designated in X Settings?

Thanks @paperManu for any suggestions!

**Comment by KevinCain** [comment]
When I abandon the two-screen X Server setup, I **am** able to address a single projector in the expected way, as noted in other [issue note](https://github.com/paperManu/splash/issues/68).

So, the problem I'm having is when the GUI and projector windows are on different X Server screens, as assigned via 'sudo nvidia-settings', and writing to `/etc/X11/xorg.conf`.

**Comment by paperManu** [comment]
In the Blender addon, the 'GPU' node corresponds to a XScreen. So you have to create a GPU node for each XScreen, and set the id accordingly.
Also, each XScreen has its own origin. So to put a window in the second XScreen (which would have the id 1), you would need to set its position to (0, 0).

**Comment by KevinCain** [comment]
Your point about the 1:1 mapping of GPU Splash nodes to X Server screens is quite useful, since I didn't catch in the documentation.  I'll close this issue and see if a fresh test clears that up in my mind.  Thanks once again!
