### ISSUE TITLE
Unable to export configuration with multiple meshes 

### ISSUE THREAD

**Issue by KevinCain** [paperManu/splash#69]
In [this thread](https://github.com/paperManu/splash/issues/65), @paperManu suggested that a good way to mask a projection surface was to use un-mapped objects.

I've tried to test that approach, but am unable to successfully export a .JSON configuration with two or more meshes referenced from the Blender 3D view.

Below I've connected two mesh+object groups to geometry from Blender:

![image](https://user-images.githubusercontent.com/5424003/51797812-12d61180-21bf-11e9-8ebe-f822ed09c8d5.png)

I'm able to export the above configuration.

However, once I connect the mesh output link to the object input (see the highlighted node below), the configuration will no longer export when via 'World:Export configuration':

![image](https://user-images.githubusercontent.com/5424003/51797929-b0314580-21bf-11e9-86f1-deb5df383d42.png)

I take it I'm adding the second geometry incorrectly.  I've tried, also unsuccessfully, to add the second mesh output directly to the first object node, as below:

![image](https://user-images.githubusercontent.com/5424003/51797950-38afe600-21c0-11e9-94aa-b2bb22337099.png)

What is the correct way to import multiple meshes into Splash?

**Comment by paperManu** [comment]
Your first try was the good one: each mesh must be connected to a different object.

I suspect that your second mesh (for the mask) has no UV coordinates, which may well be what prevents the export of the configuration. The message should be visible in the console if you ran Blender from the command line.

I agree that the Blender addon needs some love, and in particular the error messages are not very visible / complete.

**Comment by KevinCain** [comment]
Your intuition was absolutely right; the imported UVs were halting the export, but setting new UVs in Blender did the trick.  Thanks again!
