### ISSUE TITLE
Install with MacPorts

### ISSUE THREAD

**Issue by mike-iv** [paperManu/splash#7]
Hello! 
Install with macports, at first had problems with syphon. I copied lost files to the correct directory and syphon started to work, but still something wrong. Please help me :)

Check dependencies

** BUILD SUCCEEDED **

/Applications/Xcode.app/Contents/Developer/usr/bin/make all-am
make[2]: *** No rule to make target ../external/imgui/imgui.cpp', needed bylibsplash_0.3_la-imgui.lo'. Stop.
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

**Comment by paperManu** [comment]
Did you update the submodules, as detailed in [the wiki](https://github.com/paperManu/splash/wiki/Installation):
```
git submodule update --init
```

**Comment by mike-iv** [comment]
Yes, I did it. After that, I input   ./autogen.sh && ./configure 
and see several warnings and otool error at the end.

clang: warning: -framework Syphon: 'linker' input unused
texture_syphon_client.mm:41:72: warning: 'stringWithCString:' is deprecated: first deprecated in OS X
      10.4 [-Wdeprecated-declarations]
        serverMatches = [sharedDirectory serversMatchingName:[NSString stringWithCString:serverN...
                                                                       ^
/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:363:1: note: 'stringWithCString:' has
      been explicitly marked deprecated here
+ (id)stringWithCString:(const char *)bytes NS_DEPRECATED(10_0, 10_4, 2_0, 2_0);
^
texture_syphon_client.mm:43:84: warning: 'stringWithCString:' is deprecated: first deprecated in OS X
      10.4 [-Wdeprecated-declarations]
        serverMatches = [sharedDirectory serversMatchingName:nil appName:[NSString stringWithCSt...
                                                                                   ^
/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:363:1: note: 'stringWithCString:' has
      been explicitly marked deprecated here
+ (id)stringWithCString:(const char *)bytes NS_DEPRECATED(10_0, 10_4, 2_0, 2_0);
^
texture_syphon_client.mm:45:72: warning: 'stringWithCString:' is deprecated: first deprecated in OS X
      10.4 [-Wdeprecated-declarations]
        serverMatches = [sharedDirectory serversMatchingName:[NSString stringWithCString:serverN...
                                                                       ^
/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:363:1: note: 'stringWithCString:' has
      been explicitly marked deprecated here
+ (id)stringWithCString:(const char *)bytes NS_DEPRECATED(10_0, 10_4, 2_0, 2_0);
^
texture_syphon_client.mm:45:120: warning: 'stringWithCString:' is deprecated: first deprecated in OS X
      10.4 [-Wdeprecated-declarations]
  ...serversMatchingName:[NSString stringWithCString:serverName] appName:[NSString stringWithCString:...

otool: error: unable to find utility "otool", not a developer tool or in PATH
Cannot find file ./splash.app/Contents/MacOS/splash to read its dependencies
make[1]: *** [install] Error 1
make: *** [install-recursive] Error 1

**Comment by paperManu** [comment]
Can you try building the App bundle directly from the script at the root at the sources:
```
./build_osx.sh
```

Also, I never tried compiling Splash on OSX 10.11, so that may be the source of your problem. If it really does not work, did you see that there are some pre-built packages on the [release page](https://github.com/paperManu/splash/releases) ([splash.app.tar.bz2](https://github.com/paperManu/splash/releases/download/0.3.8/splash.app.tar.bz2)).

**Comment by mike-iv** [comment]
I compiling Splash on OSX 10.9.5 now I use pre-built package and splash began work, but i see only main window and dont understand how i can control splash?
![splash_1](https://cloud.githubusercontent.com/assets/16124856/11592450/8fcffd9e-9aaf-11e5-8e3e-8d9fea7e17f9.png)

**Comment by paperManu** [comment]
You can get started with the [walkthrough page](https://github.com/paperManu/splash/wiki/Walkthrough).

Note that the GUI is not ideal yet. The next revision will get a better (simplified) one. Don't hesitate to got the the ##splash channel on Freenode to ask for help. I'm usually connected, although it may take time for me to answer.

**Comment by mike-iv** [comment]
Ok! Thank you!
