### ISSUE TITLE
Setting up a game controller to work with Splash

### ISSUE THREAD

**Issue by KevinCain** [paperManu/splash#71]
@paperManu has written in [this thread](https://github.com/paperManu/splash/issues/68) that using a game controller can cause the alignment crosshairs to move on their own.

However, from the Splash code I gather that generic game controller buttons are mapped to commonly used alignment selections.

It would be nice to use a controller in this way, and I gather users are routinely doing this now.

Is there any configuration needed to get it a controller to work with Splash?  On a lark, I plugged a generic 8-button controller into a system running Splash but didn't see any effect from the buttons.  Do we need to explicitly keymap these in an external program to Splash shortcuts, or are the buttons checked directly?

**Comment by paperManu** [comment]
The controller should work out of the box. The main axis should move the calibration target, and the various buttons should allow you to change which point to control. There is a small help in the 'Shortcuts' panel.
![image](https://user-images.githubusercontent.com/1152750/51938650-a1bf7580-23db-11e9-9aad-81deefa8a3b8.png)
