### ISSUE TITLE
Working effectively with Warps in Splash

### ISSUE THREAD

**Issue by KevinCain** [paperManu/splash#74]
I've been using Splash's Warp lattice a bit over the past days and wonder if any of the basic ideas below is already implemented?

- Is there a way to reset a warp to the default lattice points?
- It seems we cannot pull warp handles beyond the yellow rectangular frame.  Is there a way to pull outer edge regions?
- Is there a way to undo one or more warp point moves?
- Is it possible to constrain a warp on one axis (e.g, by pressing a key while dragging)?  I currently use the arrow keys, which works fairly well but isn't as free as click-dragging.

**Comment by KevinCain** [comment]
@paperManu pointed out that resizing a warp lattice will reset it -- a nice trick.

**Comment by KevinCain** [comment]
I'm closing this, but note that I cannot pull warp handles beyond the yellow rectangular frame bounding the projection.  I understand this is a special case, but helpful when nudging the very corners of the image.

**Comment by paperManu** [comment]
It is indeed possible to move a warp handle beyond the frame:
* by selected the point and moving it using the arrow keys (note that the mouse pointer must hover the camera render in the GUI)
* by left-clicking close to a warp handle (but not exactly on it): the closest warp handle will then be selected and moved

Here is a screenshot showing such warp handles outside the frame of the camera:
![2019-02-05_21-19-37](https://user-images.githubusercontent.com/1152750/52316933-cabba980-298b-11e9-8e4f-46143b6b1c99.png)
